### PR TITLE
MULTIARCH-5164: Update powervs-utils regions to include us-south and tor

### PR DESCRIPTION
**Pull request by AshwinHIBM**
The latest version of `powervs-utils` includes some new zones. Update the version to this.

### CODE REVIEW

**Comment by AshwinHIBM** [comment]
/retitle [MULTIARCH-5164](https://issues.redhat.com//browse/MULTIARCH-5164): Update powervs-utils regions to include us-south and tor

**Comment by flavianmissi** [comment]
Hi @AshwinHIBM , it looks like you missed running `go mod tidy && go mod vendor` - that's why the tests are failing.

**Comment by AshwinHIBM** [comment]
> Hi @AshwinHIBM , it looks like you missed running go mod tidy && go mod vendor - that's why the tests are failing.

Thanks, indeed I had. Let's hope it works now.

**Comment by flavianmissi** [comment]
@AshwinHIBM this PR will also need docs and PX approval. Is there any need for documentation from your team's end? Is there anyone from product experience (PX) we'd want to ping? 

@xiuwang can help us with QE approval. Please let us know if you need any details, Xiujuan.

**Comment by mjturek** [comment]
@flavianmissi nothing needed on documentation or product-experience IMO. This will simply expand the number of valid zones to match what's in the installer.

**Comment by flavianmissi** [comment]
Makes sense @mjturek! I'll add the labels in that case.

/label docs-approved 
/label px-approved

**Comment by xiuwang** [comment]
Hi @juliemathew , could u give a hand to provide the cluster on power-vs platform?

**Comment by xiuwang** [comment]
/label qe-approved
Cluster-bot can't build multi-arch image from PR, I will test after this code merged. 
Then @pranavgaikwad could provide me the cluster, thank you.

**Pull request merged**
