### PR TITLE
Power VS: Use IBM COS as storage backend

### PR DESCRIPTION
**Pull request by mjturek**

### CODE REVIEW

**Review by clnperez — COMMENTED** [review]
lgtm. i think it makes sense to move the `case configapiv1.PowerVSPlatformType:` as a fallthrough with the IBMCloud one. not sure if the maintainers prefer this or having everything pulled out and alphabetized though

**Comment by mjturek** [comment]
> lgtm. i think it makes sense to move the `case configapiv1.PowerVSPlatformType:` as a fallthrough with the IBMCloud one. not sure if the maintainers prefer this or having everything pulled out and alphabetized though

Good point! It's probably cleaner to include it with the IBMCloud one

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by flavianmissi** [comment]
@mjturek is there an existing jira ticket tracking this change? we often associate PRs with them by adding their id in the PR title.

**Comment by mjturek** [comment]
closing in favor of https://github.com/openshift/cluster-image-registry-operator/pull/843

**Pull request closed without merging**
