### PR TITLE
Bug 1733902: Retry container creation on correct ServiceCode

### PR DESCRIPTION
**Pull request by coreydaley**
Looks like we were not watching for the correct service code so
that we could retry the container creation with a different name

https://bugzilla.redhat.com/show_bug.cgi?id=1733902

### CODE REVIEW

**Comment by coreydaley** [comment]
> /approve
> 
> Can we add testing for this (unit or an e2e?)

Unfortunately there is really no way to do that.  It can't be covered by a unit test, and we need Azure credentials to test creating a container.

**Comment by adambkaplan** [comment]
/lgtm

Once `e2e-azure` is working we can set up an e2e for this.

**Comment by coreydaley** [comment]
/retest
unrelated failures

**Pull request merged**
