### PR TITLE
Use cloud credentials secret

### PR DESCRIPTION
**Pull request by coreydaley**
Use the secret provided by the cloud credentials minter

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm

our tests should fail this if the creds aren't working right.

**Comment by bparees** [comment]
@jwforres fyi. @coreydaley jumped on this.

**Comment by coreydaley** [comment]
@bparees we need additional permissions, i have submitted https://github.com/openshift/cloud-credential-operator/pull/14 to add them

**Comment by coreydaley** [comment]
https://github.com/openshift/cloud-credential-operator/pull/14 merged.  I did a clean install on aws and it's not using the new information yet.  I'll try it again later or tomorrow

**Comment by bparees** [comment]
probably didn't make it into a release payload yet.  i think those get built hourly and only if they pass testing.

**Comment by coreydaley** [comment]
Looks like the CredentialsRequest is correct now, hopefully this one will pass tests soon

**Comment by coreydaley** [comment]
@bparees ptal, added a retry if it can't find new cloud credentials secret right away

**Comment by coreydaley** [comment]
These tests should start passing once the new image is built with the correct s3 permissions request

**Pull request merged**
