### PR TITLE
IR-408: request individual permissions for gcs

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by flavianmissi** [comment]
this work is currently blocked by CCO-430.
/hold

**Comment by flavianmissi** [comment]
This change is not user-facing.
/label docs-approved
/label px-approved
Tests are passing so we're good to go (pending QE review).
/hold cancel

**Comment by flavianmissi** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn

**Comment by flavianmissi** [comment]
payload test failed: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-image-registry-operator-935-ci-4.15-e2e-gcp-ovn/1722202035173986304
/hold

**Comment by wewang58** [comment]
did regression test,no critical issue found

**Comment by flavianmissi** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn

**Comment by flavianmissi** [comment]
payload job passed, this should be ready to merge.

**Pull request merged**
