### PR TITLE
Bug 1893956: Make /etc/pki/ca-trust/extracted writable

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
@dmage looks like a unit test needs to be updated to expect the new mount

**Comment by dmage** [comment]
/hold
It seems it doesn't work

**Comment by dmage** [comment]
`update-ca-trust` expects that `/etc/pki/ca-trust/extracted/pem` and other directories already exist.

**Comment by bparees** [comment]
i guess you could make the init script create those dirs, in the registry image.

**Comment by dmage** [comment]
/hold cancel
This one seems to work.

**Pull request merged**
