### PR TITLE
OCPBUGS-24649: add private endpoint permissions to Azure credentials request

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by flavianmissi** [comment]
and we want QE approval before merging this one
/hold

**Comment by wewang58** [comment]
Thanks @jinyunma help to verify the bug
/label qe-approved

**Comment by wewang58** [comment]
Thanks @jinyunma help to verify the bug
/label qe-approved

**Comment by flavianmissi** [comment]
test error is unrelated to the changes:
```
error: unable to create a release: operator "cluster-cloud-controller-manager-operator" contained an invalid image-references file: no input image tag named "alibaba-cloud-controller-manager"
```
I've reported it to the CCO team, let's give them a chance to fix.

**Pull request merged**
