### PR TITLE
[release-4.17] OCPBUGS-38538: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

### PR DESCRIPTION
**Pull request by sdodson**
Clean picks from #1095 

The bot apparently can't open PRs above a certain size.

### CODE REVIEW

**Comment by sdodson** [comment]
/retitle OCPBUGS-38538: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

**Comment by sdodson** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-serial periodic-ci-openshift-release-master-ci-4.17-upgrade-from-stable-4.16-e2e-azure-ovn-upgrade periodic-ci-openshift-release-master-ci-4.17-e2e-azure-ovn-upgrade

**Comment by sdodson** [comment]
Hmm, `go mod tidy` is failing with unknown checksum for gophercloud. I'm not sure what to do about that.
@flavianmissi feel free to close this and open your own PR if you know the correct path forward here. I was just hoping to have this ready to merge when you came in tomorrow but I'm not sure what to do.


```
~/git/cluster-image-registry-operator (release-4.17) go mod tidy
go: downloading github.com/gophercloud/gophercloud v1.1.0
go: downloading google.golang.org/api v0.172.0
go: downloading github.com/gophercloud/utils v0.0.0-20221124081324-7bac6f5cdf99
go: downloading github.com/google/uuid v1.6.0
verifying github.com/gophercloud/gophercloud@v1.1.0: checksum mismatch
	downloaded: h1:DTmJ9UBQ294zo+EQj4s9/dbBx13y7NwXyQ/Bs/09LVE=
	go.sum:     h1:xlsBMeBi0KJ56RBW6GJ2laJJKbtlpObj5HwQzggYAsA=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by flavianmissi** [comment]
/retitle [release-4.17] OCPBUGS-38538: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

**Comment by flavianmissi** [comment]
Running go mod after downloading the changes on this PR worked for me 🤔 I guess the failure could be due to some go mod cache (either on my machine or yours).
Since I can't modify this PR, I'll close it and open a new one with the same changes plus the go mod tidy.

/close

**Pull request closed without merging**
