### PR TITLE
Use annotation to request proxy configuration injection from the cvo

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
/hold
need to update the test to check the deployment after the injection occurrs

**Comment by adambkaplan** [comment]
/approve

/retest

Looks like infra flakes for e2e-aws tests

**Comment by coreydaley** [comment]
@adambkaplan I think this one is ready for a look now.

**Comment by coreydaley** [comment]
/retest
unrelated test failures

**Pull request merged**
