### PR TITLE
Bug 1769691: Report Available when registry is explicitly Removed

### PR DESCRIPTION
**Pull request by ricardomaraschini**
[This](https://github.com/openshift/cluster-image-registry-operator/pull/387) PR was not back ported to `release-4.1` and we are not not able to proceed with cluster updates. As I could not cherry-pick directly from the PR(merge conflicts) I am submitting it as a new one.

### CODE REVIEW

**Comment by bparees** [comment]
@ricardomaraschini the 4.2 BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1770658) had two PRs associated:
https://github.com/openshift/cluster-image-registry-operator/pull/408
https://github.com/openshift/cluster-image-registry-operator/pull/412

This PR does not seem to include the changes from #408, are they not needed to resolve this?

**Comment by ricardomaraschini** [comment]
> @ricardomaraschini the 4.2 BZ (https://bugzilla.redhat.com/show_bug.cgi?id=1770658) had two PRs associated:
> #408
> #412
> 
> This PR does not seem to include the changes from #408, are they not needed to resolve this?

The BZ I refer on this PR does include #408 changes, cherry-picked as #409. This happened because @dmage and me where working on two separated PRs(with overlapping areas) and one of them(this one, originally #387) did not got backported as far as 4.1.

**Comment by bparees** [comment]
@ricardomaraschini thanks for the explanation, approving

**Comment by adambkaplan** [comment]
@ricardomaraschini is there a new PR which replaces this one?

**Comment by dmage** [comment]
This PR was merged: https://github.com/openshift/cluster-image-registry-operator/commit/7d8f4dd782fc82e38eee2b8f09c4f5e74da3d1f6

**Pull request closed without merging**
