### PR TITLE
[release-4.16] OCPBUGS-39098: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

### PR DESCRIPTION
**Pull request by flavianmissi**
**Note for QE**
Because 4.16 is GA, we cannot backport the "containers/delete" permission. @rajdeepc2792 has wrote the code in a way that storage account deletion should still proceed [when setting `managementState: Removed`] even after container deletion fails due to lack of permission, so please double check that is the case. If you find that not to be the case, we will still go ahead with this backport but we will create a pre-emptive bug describing the issue with a documented workaround (which we will need to figure out). Though I'm hoping it won't come to that 😅

### CODE REVIEW

**Comment by sdodson** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-serial periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-azure-ovn-upgrade periodic-ci-openshift-release-master-ci-4.16-e2e-azure-ovn-upgrade

**Comment by flavianmissi** [comment]
`e2e-azure-ovn` failures don't seem related to the changes here - various test seem to be timing out, including one image registry related test but as I said it still don't seem related:
```
: [sig-imageregistry][Feature:ImageAppend] Image append should create images by appending them [apigroup:image.openshift.io] [Skipped:Disconnected] [Skipped:NoOptionalCapabilities] [Suite:openshift/conformance/parallel] expand_less 	3m5s
{  fail [k8s.io/kubernetes@v1.29.0/test/e2e/framework/pod/pod_client.go:245]: wait for pod "append-test" to succeed
Expected success, but got an error:
    <framework.FailureError>: 
    Timed out after 180.001s.
    The matcher passed to Eventually returned the following error:
        <*errors.errorString | 0xc001c8c950>: 
        pod "append-test" failed with reason: "", message: ""
        {
            s: "pod \"append-test\" failed with reason: \"\", message: \"\"",
        }
    {
        msg: "Timed out after 180.001s.\nThe matcher passed to Eventually returned the following error:\n    <*errors.errorString | 0xc001c8c950>: \n    pod \"append-test\" failed with reason: \"\", message: \"\"\n    {\n        s: \"pod \\\"append-test\\\" failed with reason: \\\"\\\", message: \\\"\\\"\",\n    }",
        fullStackTrace: "k8s.io/kubernetes/test/e2e/framework/pod.WaitForPodCondition({0x95fa468, 0xda37700}, {0x964f110?, 0xc001571a00?}, {0xc000a57fa0, 0x1b}, {0xc001677090, 0xb}, {0xc001572978, 0x13}, ...)\n\tk8s.io/kubernetes@v1.29.0/test/e2e/framework/pod/wait.go:227 +0x393\nk8s.io/kubernetes/test/e2e/framework/pod.(*PodClient).WaitForSuccess(0xc001b7f4a0, {0x95fa468, 0xda37700}, {0xc001677090, 0xb}, 0x1?)\n\tk8s.io/kubernetes@v1.29.0/test/e2e/framework/pod/pod_client.go:234 +0x157\ngithub.com/openshift/origin/test/extended/images.glob..func1.2()\n\tgithub.com/openshift/origin/test/extended/images/append.go:119 +0x38a",
    }
Ginkgo exit error 1: exit with code 1}
```

I also looked at the must-gather of the [latest run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-image-registry-operator/1104/pull-ci-openshift-cluster-image-registry-operator-release-4.16-e2e-azure-ovn/1828720413069283328) and as far as I can tell the cluster operator is Available:
```
status:
  conditions:
  - lastTransitionTime: "2024-08-28T10:03:15Z"
    message: |-
      Available: The registry is ready
      NodeCADaemonAvailable: The daemon set node-ca has available replicas
      ImagePrunerAvailable: Pruner CronJob has been created
    reason: Ready
    status: "True"
    type: Available
  - lastTransitionTime: "2024-08-28T10:03:55Z"
    message: |-
      Progressing: The registry is ready
      NodeCADaemonProgressing: The daemon set node-ca is deployed
    reason: Ready
    status: "False"
    type: Progressing
  - lastTransitionTime: "2024-08-28T10:02:06Z"
    reason: AsExpected
    status: "False"
    type: Degraded
```
Logs also look fine.

**Comment by rajdeepc2792** [comment]
@flavianmissi @sdodson Confirmed the changes here, everything seems correct and as expected in the PR.

**Pull request merged**
