### PR TITLE
[release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate

### PR DESCRIPTION
**Pull request by mandre**
This is a backport of #445.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@mandre is there a reason why the cherrypick bot wasn't used against the original PR?

**Comment by mandre** [comment]
> @mandre is there a reason why the cherrypick bot wasn't used against the original PR?

No reason in particular other than I had a bunch of backports in multiple repos, sometimes adding multiple PRs at the same time. CIRO wasn't one of the repos where I combined the commits of multiple PRs into one, so I could effectively have used the cherry-pick-bot.

**Comment by sdodson** [comment]
/assign @adambkaplan 
PTAL

**Pull request merged**
