### PR TITLE
Apply ClusterOperator even if everything is bad

### PR DESCRIPTION
**Pull request by legionus**
Fixes [BZ#1704590](https://bugzilla.redhat.com/show_bug.cgi?id=1704590)

### CODE REVIEW

**Comment by coreydaley** [comment]
Did we want to pull #273 into this PR?

**Comment by legionus** [comment]
> Did we want to pull #273 into this PR?

@coreydaley No, because our tests are not ready for such tests. For example `TestAWSChangeS3Encryption`:
```yaml
framework.go:44: the latest observed state of the image registry resource:
		metadata:
		  creationTimestamp: "2019-05-03T09:52:34Z"
		  finalizers:
		  - imageregistry.operator.openshift.io/finalizer
		  generation: 2
		  name: cluster
		  resourceVersion: "36221"
		  selfLink: /apis/imageregistry.operator.openshift.io/v1/configs/cluster
		  uid: 2d43bfc1-6d89-11e9-88a5-12e088040a6c
		spec:
		  defaultRoute: false
		  httpSecret: ef760b9448f8db9ad33e0db5a3bef2bac624aab7ca761e856f137c02715cc1956449abd0c2d3577f72bc71a36a1730c824925ef169f3a66b691ac5c7efdadc68
		  logging: 2
		  managementState: Managed
		  proxy:
		    http: ""
		    https: ""
		    noProxy: ""
		  readOnly: false
		  replicas: 1
		  requests:
		    read:
		      maxInQueue: 0
		      maxRunning: 0
		      maxWaitInQueue: 0s
		    write:
		      maxInQueue: 0
		      maxRunning: 0
		      maxWaitInQueue: 0s
		  storage:
		    s3:
		      bucket: image-registry-us-east-1-f339e0a7f533499bb04b6712723f9db1-2d46
		      encrypt: false
		      keyID: ""
		      region: us-east-1
		      regionEndpoint: ""
		status:
		  conditions:
		  - lastTransitionTime: "2019-05-03T09:57:25Z"
		    message: "InvalidAccessKeyId: The AWS Access Key Id you provided does not exist
		      in our records.\n\tstatus code: 403, request id: CC32FC9864C84237, host id:
		      ZLJwO0j/BXrBCF/zsEwFSmRqrT2frRGYtJlMmFE/Tap/jTqyJo8bixDcFKtShwEvXbBhBI3c9W0="
		    reason: InvalidAccessKeyId
		    status: "False"
		    type: StorageExists
		  - lastTransitionTime: "2019-05-03T09:52:34Z"
		    message: The deployment does not exist
		    reason: DeploymentNotFound
		    status: "False"
		    type: Available
		  - lastTransitionTime: "2019-05-03T09:52:34Z"
		    message: "Unable to apply resources: unable to sync storage configuration: InvalidAccessKeyId:
		      The AWS Access Key Id you provided does not exist in our records.\n\tstatus
		      code: 403, request id: CC32FC9864C84237, host id: ZLJwO0j/BXrBCF/zsEwFSmRqrT2frRGYtJlMmFE/Tap/jTqyJo8bixDcFKtShwEvXbBhBI3c9W0="
		    reason: Error
		    status: "True"
		    type: Progressing
		  - lastTransitionTime: "2019-05-03T09:52:34Z"
		    status: "False"
		    type: Degraded
		  - lastTransitionTime: "2019-05-03T09:52:34Z"
		    status: "False"
		    type: Removed
		  observedGeneration: 2
		  readyReplicas: 0
		  storage: {}
		  storageManaged: false
```
with such errors we will never reach "normal" status in the clusteroperator.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/274/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/1440

**Comment by legionus** [comment]
> https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/274/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/1440

Nevermind. Tests from #273 broken. I added my own tests.

**Comment by legionus** [comment]
@dmage please review.

**Pull request merged**
