### PR TITLE
OCPVE-632: add capability annotations to manifests

### PR DESCRIPTION
**Pull request by qJkee**
Add capability annotation to manifests to make image registry optional

### CODE REVIEW

**Comment by flavianmissi** [comment]
Thanks for this @qJkee. Could you look at the test failures?
Additionally, it seems you changed a file that is auto-generated (that's why the verify job is failing).

**Comment by flavianmissi** [comment]
thank you @qJkee ! 

> The rest of the tests would be working once the installer and CVO will know about this capability
Gotcha. Is the plan to change installer and CVO before merging this PR?

**Comment by flavianmissi** [comment]
Also - do we need resources created at runtime by the operator to also have this capability? I'm assuming we don't need that but want to confirm.

**Comment by flavianmissi** [comment]
should we put this PR on hold then to signalize that we are waiting?

**Review by flavianmissi — COMMENTED** [review]
Does the `manifests/01-registry-credentials-request-powervs.yaml` file also need to get the capabilities annotation?
Looks good otherwise

**Comment by wking** [comment]
[e2e-aws-operator run failed on a build-cluster hiccup][1].

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/856/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/1696620838209458176

**Comment by flavianmissi** [comment]
same error failure as previous
/retest-required

**Comment by flavianmissi** [comment]
test failure seems unrelated
/retest-required

**Pull request merged**
