### PR TITLE
OCPBUGS-32491: Power VS: Add support for Power VS endpoint overrides

### PR DESCRIPTION
**Pull request by mjturek**

### CODE REVIEW

**Comment by mjturek** [comment]
> hey @mjturek, there are some valid failures showing up in the tests (build time):
> 
> ```
> pkg/storage/ibmcos/ibmcos.go:473:31: undefined: configapiv1.IBMCloudServiceEndpoints) (typecheck)
> 	"github.com/openshift/cluster-image-registry-operator/pkg/storage/ibmcos"
> 	^
> pkg/operator/nodecadaemon.go:8:2: "k8s.io/api/apps/v1" imported as appsv1 and not used (typecheck)
> 	appsv1 "k8s.io/api/apps/v1"
> 	^
> ```
> 
> Maybe you need to bump `github.com/openshift/api` ?

I had thought the Power VS endpoints were of type IBMCloudServiceEndpoint, but unfortunately they're of type PowerVSServiceEndpoint. Functionally the same thing, but can't be used interchangably.

New solution is a bit ugly but best I can think of

**Comment by flavianmissi** [comment]
Changes look pretty reasonable to me. I'd like us to test this pre-merge to be on the safe side (things on the image registry side have been a bit rocky lately).
@xiuwang is image registry QE. Xiujuan, do need to connect with power VS QE to verify this? Let us know if we can help.
/assign @xiuwang

**Comment by flavianmissi** [comment]
/lgtm
/hold
holding for pre-merge tests

**Comment by flavianmissi** [comment]
@mjturek if you want to retest all the command is `/test all`. see https://prow.k8s.io/command-help for more

**Comment by mjturek** [comment]
> @mjturek if you want to retest all the command is `/test all`. see https://prow.k8s.io/command-help for more

Thanks! I am trying to list all available tests but I have been trying locally instead

**Comment by juliemathew** [comment]
qe-approved

**Comment by flavianmissi** [comment]
I think the correct command is `/label qe-approved` @juliemathew

**Pull request merged**
