### PR TITLE
[release-4.4] Bug 1826033: Bootstrap as suspended

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by adambkaplan** [comment]
/retitle [release-4.4] Bug 1826033: Bootstrap as suspended

**Comment by adambkaplan** [comment]
/hold

Need to fix the prometheus alerts test.

**Comment by adambkaplan** [comment]
Patch manager note - needs https://github.com/openshift/origin/pull/24901 to merge first.

**Comment by bparees** [comment]
@coreydaley please make sure you unhold this the second the origin test changes land.

**Comment by bparees** [comment]
/hold

sorry, thought what this needed merged but it was something else.

**Pull request merged**
