### PR TITLE
Fix PVC access mode validation 

### PR DESCRIPTION
**Pull request by legionus**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1700294
/assign @dmage

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@legionus RWX is not supported by most provisioners, hence this change basically makes PVC as source useless. What about instead setting `.Spec.Strategy: Recreate` on the registry deployment?

**Comment by dmage** [comment]
@alvaroaleman we don't want to have downtimes during upgrades and configuration changes. Which cloud platform do you use and what volume plugin do you want to use for your persistent volume?

**Comment by alvaroaleman** [comment]
@dmage I am using vsphere and would like to use its volumes.

**Pull request merged**
