### PR TITLE
OCPBUGS-3974: check for nil pointer before dereferencing

### PR DESCRIPTION
**Pull request by flavianmissi**
a customer reported seeing this on OCP 4.10 - not sure why it hasn't shown up before tbh

### CODE REVIEW

**Comment by dmage** [comment]
@flavianmissi please add the Jira ticket to the title

**Comment by flavianmissi** [comment]
@dmage there is no jira ticket - do we require one to merge?

**Comment by dmage** [comment]
@flavianmissi yes, for bug fixes we need a BZ or a Jira bug, for new features we need a Jira story.

**Comment by flavianmissi** [comment]
fixed, PTAL @dmage

**Pull request merged**
