### PR TITLE
add current profile annotations to CVO manifests

### PR DESCRIPTION
**Pull request by guillaumerose**
This is matches openshift/enhancements#414 and doesn't change existing behavior

### CODE REVIEW

**Comment by dmage** [comment]
/hold
until the enhancement proposal is merged.

**Comment by deads2k** [comment]
The name has been explicitly merged in https://github.com/openshift/enhancements/pull/510 .  This is consistent with the current state of the enhancement.  #414 will help describe future CVO input, but the handling is already in place for this default profile.

/lgtm

**Pull request merged**
