### PR TITLE
Bump(*): openshift/api

### PR DESCRIPTION
**Pull request by coreydaley**
Fixes
`unable to sync: Config.imageregistry.operator.openshift.io "cluster" is invalid: spec.storage.azure.container: Invalid value: "": spec.storage.azure.container in body should be at least 3 chars long, requeuing`

### CODE REVIEW

**Comment by coreydaley** [comment]
/retest
```
level=error msg="Cluster operator monitoring Degraded is True with UpdatingPrometheusK8SFailed: Failed to rollout the stack. Error: running task Updating Prometheus-k8s failed: waiting for Prometheus object changes failed: waiting for Prometheus: expected 2 replicas, updated 0 and available 0"
level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is still updating"
```

**Comment by coreydaley** [comment]
Probably should have held that for the e2e-azure test to pass first, oh well.

**Comment by adambkaplan** [comment]
@hexfusion we need to create a separate PR that bumps openshift/api against the release-4.4 branch.

**Comment by coreydaley** [comment]
@hexfusion @adambkaplan https://github.com/openshift/cluster-image-registry-operator/pull/519

**Pull request merged**
