### PR TITLE
Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

### PR DESCRIPTION
**Pull request by rajdeepc2792**
Fixes:-
https://issues.redhat.com/browse/OCPBUGS-37543
&
https://issues.redhat.com/browse/ARO-9391

Changes:-
For Azure based storage account operations the Image Registry Operator is still using Azure Storage Account Access Keys generated using the Storage Accounts Client for manual mode credentials(i.e Managed Identity/Federated Identity).
This PR adds a diversion flow in operator when using federated tokens for all non Azure Stack Cloud to perform below operations:-
1. When creating storage account, disable the Shared Key Access.
2. When interacting with storage container use RBAC based authentication instead of using Shared Access Keys.

Testing:-
- Unit Test Case:- No new test cases are added for the changes(Need to be performed)
- Testing on 4.15 Managed Identity Cluster:-
    - Edited operator's deployment object to point the image to custom image-registry-operator image.
    - Operator and Registry pods got created and stayed in Running status successfully.
    - Operator and Registry pod was able to perform the operations on Storage Account and Container without fetching the Access Keys
    - Changing the AccountName in imageregistry.operator config created a new storage account with Shared Key Access disabled and container was also created successfully.

### CODE REVIEW

**Review by kimorris27 — COMMENTED** [review]
The changes make sense to me from an ARO SRE perspective, though I'd defer to those who work on the image registry operator for a more comprehensive review.

**Comment by flavianmissi** [comment]
Seems like the [unit tests](https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/storage/azure/azure_test.go?plain=1#L291-L294) don't set a `azure_tenant_id`, which the [`azureclient` package](https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/storage/azure/azureclient/azureclient.go?plain=1#L699-L701) judges to be an invalid configuration.
I'm not actually sure if the tenant id should be required - do you happen to know @rajdeepc2792 ?
If the tenant id isn't required then the validation in `azureclient` needs to change. If the tenant id should be kept as required, then we should just add one to the tests.

**Comment by flavianmissi** [comment]
the e2e-azure-operator failure seems like a flake.
the hypershift ones I'm not sure - I could not determine the root cause of the failure. will trigger a retest and if that fails in the same I'll ping the hypershift team for help.
Raj will fix unit tests when he gets the time.

/test e2e-azure-operator
/test e2e-hypershift
/test e2e-hypershift-conformance

**Comment by flavianmissi** [comment]
All 3 retests failed due to CI issues:
```
{  error occurred handling build cluster-image-registry-operator-amd64: could not get build cluster-image-registry-operator-amd64: client rate limiter Wait returned an error: context canceled}
```
Will try again tomorrow.

**Comment by flavianmissi** [comment]
Looks like Hypershift failures were related to infra: https://redhat-external.slack.com/archives/C01C8502FMM/p1722861999702859

/test e2e-azure-operator
/test e2e-hypershift
/test e2e-hypershift-conformance

**Comment by rajdeepc2792** [comment]
Performed changes in the fork branch, but for some reason the PR is not able to recognize the changes done. Probably due to prow being slow. I will create a new PR in case there's no progress over the weekend.

**Comment by rajdeepc2792** [comment]
Created a new PR for the same as no progress in CI after rebase:- https://github.com/openshift/cluster-image-registry-operator/pull/1087

**Pull request closed without merging**
