### PR TITLE
Create image-registry deployment by default

### LINKED ISSUE #34: need to retry failed deploymentconfig rollouts or switch to deployments
Upstream deployments constantly try to rollout the latest state until explicitly asked not to.  DeploymentConfigs give up unless triggered again.  Given an operator managed deploymentconfig that should be actively reconciled, you should be retrying failed deployments since they can later succeed.

The current state in openshift/installer is a good example where a blip in the first rollout will cause the image registry to be stuck indefinitely.  Switching to a deployment will resolve this problem.  Alternatively you can rebuild the oc rollout logic.

### PR DESCRIPTION
**Pull request by legionus**
Fixes #34

### CODE REVIEW

**Comment by legionus** [comment]
God bless flakes.
/retest

**Comment by legionus** [comment]
Life will be boring if CI will always work.
/retest

**Comment by legionus** [comment]
```
could not wait for build: the build src failed with reason PushImageToRegistryFailed: Failed to push the image to the registry.

Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: unauthorized: unable to validate token
```
/retest

**Comment by bparees** [comment]
@legionus no other changes here are required to apply config changes to the deployment (instead of deploymentconfig)?

**Comment by bparees** [comment]
> @legionus no other changes here are required to apply config changes to the deployment (instead of deploymentconfig)?

@legionus presumably because you're just modifying a podtemplatespec either way?

**Comment by legionus** [comment]
> presumably because you're just modifying a podtemplatespec either way?

Yes. Also, all other parts are almost the same.

**Pull request merged**
