### PR TITLE
[release-4.15] OCPBUGS-36325: Set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by ShazaAldawamneh**
[OCPBUGS-36325](https://issues.redhat.com/browse/OCPBUGS-36325)

Manual cherry-pick of [#1008](https://github.com/openshift/cluster-image-registry-operator/pull/1008)

### CODE REVIEW

**Review by dmage — APPROVED** [review]

**Comment by wewang58** [comment]
Installed some platform and regression, upgrade test
/label qe-approved

**Pull request merged**
