### PR TITLE
remove master node selector

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
This selector is causing frustration/confusion when people try to deploy the operator on clusters that do not have a master node labeled, or that have other default nodeselector's being applied to their resources.  Until we hear otherwise, I don't see a good reason to restrict ourselves to specifically the master node.

/assign @dmage

**Comment by dmage** [comment]
https://github.com/openshift/cluster-image-registry-operator/blob/7c61167496ab038f3294f253dbbb54b2c06b9b18/pkg/resource/podtemplatespec.go#L220

@bparees should this node selector be removed as well?

**Comment by bparees** [comment]
hm.  yes, i guess so, at least for now. will update.

**Comment by bparees** [comment]
updated, thanks @dmage

**Pull request merged**
