### PR TITLE
updating readme with project alignment changes

### PR DESCRIPTION
**Pull request by sferich888**
We changed the name of the operator docs should align

### CODE REVIEW

**Comment by dmage** [comment]
@sferich888 this is a cluster-scoped resource today, can you remove `-n openshift-image-registry`?

**Comment by coreydaley** [comment]
@sferich888 bump
Please see the comment from @dmage above.

**Comment by dmage** [comment]
Merged, https://github.com/openshift/cluster-image-registry-operator/pull/289/commits/01b984f2bcb932114abda1a631a4f8ac993dd848

**Pull request closed without merging**
