### PR TITLE
OCPBUGS-38287: bump gophercloud to latest v2

### PR DESCRIPTION
**Pull request by EmilienM**
Bump Gophercloud to the latest v2 and update the code for swift to work with this new version.

### CODE REVIEW

**Comment by flavianmissi** [comment]
Thank you for doing this! 
/lgtm
Test failures seem unrelated.
/retest

**Comment by EmilienM** [comment]
/test e2e-aws-ovn-upgrade
unrelated errors...

**Comment by EmilienM** [comment]
@flavianmissi can you please override the CI job, so we stop wasting resources. Thanks

**Pull request merged**
