### PR TITLE
Bug 1836753: Use release-4.3 api

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
We use release-4.4 API in the release-4.3 branch. We may want to backport validator annotations, `preserveUnknownFields: false`, but in this case we'll have to backport omitempty as well.

**Comment by dmage** [comment]
Waiting for https://github.com/openshift/api/pull/547 to land

**Comment by ashcrow** [comment]
I was unable to figure out why bumping api in vendor fixes the issue reading this PR as well as the bug. However, bumping has occurred in master and in 4.4 (to different versions specific to the release it looks like). In the future please consider adding the context to the PR or bug to make it easier for review and approval :pray:.

**Pull request merged**
