### PR TITLE
Set operator cpu request

### PR DESCRIPTION
**Pull request by adambkaplan**

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @bparees 
/cc @dmage 
fyi @legionus @derekwaynecarr

**Comment by adambkaplan** [comment]
looks like the operand CPU request is already set for new installs: https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/resource/podtemplatespec.go#L249

**Comment by bparees** [comment]
> looks like the operand CPU request is already set for new installs: https://github.com/openshift/cluster-image-registry-operator/blob/master/pkg/resource/podtemplatespec.go#L249

for the operand, yes.

**Pull request merged**
