### PR TITLE
Revert "Merge pull request #430 from adambkaplan/bump-api-clientgo"

### PR DESCRIPTION
**Pull request by adambkaplan**
This reverts commit 137ecaf4dfd5631dcc0ff337a54808181c8b2890, reversing
changes made to 9be9231d8e6892f505c0d2ad0e1f69da78b52278.

This changed caused clusters to fail installation on GCP

### CODE REVIEW

**Comment by adambkaplan** [comment]
@coreydaley @dmage @Fedosin Post mortem on this:

1. CI marked our aws tests as passing, even though tests did not run
2. My api bump did not include the `omitempty` tag that I thought had merged in openshift/api.

**Comment by wking** [comment]
[update][1] failed with:

```
failed to initialize the cluster: Cluster operator image-registry is still updating
```

because it's trying to launch the source cluster from the current master, and current master has the broken code.  Since this is a pure revert, can we `/override` that test?

**Comment by adambkaplan** [comment]
@bparees I think we need to green-button this. Master is broken.

**Pull request merged**
