### PR TITLE
IR-311: storage: azure: use azidentity with an adapter

### PR DESCRIPTION
**Pull request by r4f4**
ADAL is being deprecated so we need to move to azidentity.

WIP while I test Azure StackCloud.

### CODE REVIEW

**Comment by r4f4** [comment]
/retitle storage: azure: use azidentity with an adapter

**Comment by flavianmissi** [comment]
I guess we're stuck with `github.com/jongio/azidext` until we upgrade the sdk right?
/retest

**Comment by flavianmissi** [comment]
forgot to ask: do we have a JIRA ticket tracking this? if not please create one under the [IR project](https://issues.redhat.com/projects/IR/issues/), then add the number/ID to the PR title.

**Comment by r4f4** [comment]
/retitle IR-311: storage: azure: use azidentity with an adapter

**Comment by flavianmissi** [comment]
this is an internal change so users aren't affected
/label docs-approved
/label px-approved

**Comment by flavianmissi** [comment]
@xiuwang could you have a look at this one?

**Comment by xiuwang** [comment]
@flavianmissi Qe will do regression and upgrade test

**Comment by xiuwang** [comment]
Do regression for image-registry and upgrade cluster from 4.12 to pr version, image registry works well, no issue found.

**Comment by r4f4** [comment]
Rebased on top of master and fixed a typo `s/HasPrefix/HasSuffix`

**Comment by r4f4** [comment]
Hmm, I'm getting a similar error from `ci/prow/verify` 
```
verifying github.com/gophercloud/gophercloud@v1.1.0: checksum mismatch
	downloaded: h1:xlsBMeBi0KJ56RBW6GJ2laJJKbtlpObj5HwQzggYAsA=
	go.sum:     h1:DTmJ9UBQ294zo+EQj4s9/dbBx13y7NwXyQ/Bs/09LVE=
```
if I run on master:
```bash
$: go mod tidy
verifying github.com/gophercloud/gophercloud@v1.1.0: checksum mismatch
	downloaded: h1:DTmJ9UBQ294zo+EQj4s9/dbBx13y7NwXyQ/Bs/09LVE=
	go.sum:     h1:xlsBMeBi0KJ56RBW6GJ2laJJKbtlpObj5HwQzggYAsA=
```

**Comment by flavianmissi** [comment]
hey @r4f4 - this is an odd one, I tried on my local dev env (macOS, Go 1.19.1) as well on a container (docker.io/library/golang:1.19) and couldn't reproduce. Are you still seeing it?

/test verify

**Comment by r4f4** [comment]
```bash
$: curl https://sum.golang.org/lookup/github.com/gophercloud/gophercloud@v1.1.0
14036584
github.com/gophercloud/gophercloud v1.1.0 h1:xlsBMeBi0KJ56RBW6GJ2laJJKbtlpObj5HwQzggYAsA=
github.com/gophercloud/gophercloud v1.1.0/go.mod h1:aAVqcocTSXh2vYFZ1JTvx4EQmfgzxRcNupUfxZbBNDM=

go.sum database tree
14284568
iBlQuBaNy53ameYrvEi/ymV4fFMEsl+ax4zV984YnjA=

— sum.golang.org Az3grsnFLEr31lnoqtpt0Am3of1JjUCTniEadHr4xu7dw9SQdqE+fcLMQrEZ8OZxrSBX+wBCm7Ligl88ikl+P1irUw8=

$: go env GOSUMDB
off
```

**Comment by dmage** [comment]
@r4f4 as I can see, you resolved this - https://github.com/openshift/cluster-image-registry-operator/compare/7a5f906e1839b364407ab06de8b8beb2b327de67..0927eac87f8fcdcc5d4a551b2e9a2bbf353264b0
 
It seems the initial tag v1.1.0 was pointing to another commit, and it was downloaded by Go. That made the Go proxy remember v1.1.0. Then the package authors noticed the mistake (changelog is not updated), and updated the tag. The proxy doesn't care about it, it'll continue to serve the old version.

The cached version is available at https://proxy.golang.org/github.com/gophercloud/gophercloud/@v/v1.1.0.zip

**Comment by r4f4** [comment]
> @r4f4 as I can see, you resolved this - https://github.com/openshift/cluster-image-registry-operator/compare/7a5f906e1839b364407ab06de8b8beb2b327de67..0927eac87f8fcdcc5d4a551b2e9a2bbf353264b0

Yes, using a container did the trick.

> It seems the initial tag v1.1.0 was pointing to another commit, and it was downloaded by Go. That made the Go proxy remember v1.1.0. Then the package authors noticed the mistake (changelog is not updated), and updated the tag. The proxy doesn't care about it, it'll continue to serve the old version.
> 
> The cached version is available at https://proxy.golang.org/github.com/gophercloud/gophercloud/@v/v1.1.0.zip

Interesting. I'm glad it was not something I was doing wrong.

**Comment by mandre** [comment]
> @r4f4 as I can see, you resolved this - https://github.com/openshift/cluster-image-registry-operator/compare/7a5f906e1839b364407ab06de8b8beb2b327de67..0927eac87f8fcdcc5d4a551b2e9a2bbf353264b0
> 
> It seems the initial tag v1.1.0 was pointing to another commit, and it was downloaded by Go. That made the Go proxy remember v1.1.0. Then the package authors noticed the mistake (changelog is not updated), and updated the tag. The proxy doesn't care about it, it'll continue to serve the old version.
> 
> The cached version is available at https://proxy.golang.org/github.com/gophercloud/gophercloud/@v/v1.1.0.zip

Thanks for letting us know @dmage. We've just released [v1.1.1](https://github.com/gophercloud/gophercloud/releases/tag/v1.1.1) of gophercloud that fixes the issue.

**Pull request merged**
