### PR TITLE
OCPBUGS-29932: cmd/move-blobs: log and exit 1 on error instead of panic

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by deads2k** [comment]
structurally in master, I would suggest following the `oc`/`kubectl` pattern of main calling to a single function that returns errors

/lgtm

**Comment by flavianmissi** [comment]
> structurally in master, I would suggest following the oc/kubectl pattern of main calling to a single function that returns errors

Thanks, I'll keep that in mind. This command was written specifically to migrate blobs affected by a bug in 4.14 so I'm not planning on keeping it long-term.

/cherry-pick release-4.15

**Pull request merged**
