### PR TITLE
MULTIARCH-4971: Set import mode in image config based on ClusterVersion desired Architecture

### PR DESCRIPTION
**Pull request by Prashanth684**
https://github.com/openshift/api/pull/2024 introduces the architecture
property in the desired status field which indicates the architecture of
the cluster (or the architecture being reconciled to). Set import mode
 based on this status - if "Multi", set importmode to PreserveOriginal,
 else to Legacy.

### CODE REVIEW

**Comment by flavianmissi** [comment]
Thanks for doing this, and for your patience @Prashanth684 
As far as I can tell the `TestS3Minio` failure is unrelated (flaky). While looking at that failure I see this in the operator logs tho:
```
W1204 03:06:23.640401       1 warnings.go:70] unknown field "spec.imageStreamImportMode"
```
Do you know why this warning is happening?

/retest

**Comment by Prashanth684** [comment]
> Thanks for doing this, and for your patience @Prashanth684 As far as I can tell the `TestS3Minio` failure is unrelated (flaky). While looking at that failure I see this in the operator logs tho:
> 
> ```
> W1204 03:06:23.640401       1 warnings.go:70] unknown field "spec.imageStreamImportMode"
> ```
> 
> Do you know why this warning is happening?
> 
> /retest

I've seen this warning in many operators/places for fields that are featuregated and in techpreview. Once I enable tech preview, this error goes away as the CRD contains those fields. I'm not sure of the exact points in the code which triggers these errors, but suffice to say that these do seem to be benign.

**Comment by flavianmissi** [comment]
Thanks for explaining @Prashanth684 !

/lgtm

**Comment by wewang58** [comment]
Today our qe jenkins is down, will test  tomorrow when jenkins is ready.

**Comment by wewang58** [comment]
@Prashanth684 2 jobs are failed, not sure if it's has issues.

**Comment by wewang58** [comment]
@Prashanth684 I do test for single cluster, no critical issue found, because cannot build a multi-arch image with the pr, when pr is merged, will build a multi-arch cluster to post test it again.

**Comment by Prashanth684** [comment]
> @Prashanth684 I did test for single cluster, no critical issue found, because cannot build a multi-arch image with the pr, when pr is merged, will build a multi-arch cluster to post test it again.

Thanks @wewang58 ! also this is behind a featuregate so you have to enable techpreview featuregate before testing

**Pull request merged**
