### PR TITLE
MULTIARCH-4971: Sync ImageStreamImportMode setting in the image config status

### PR DESCRIPTION
**Pull request by Prashanth684**
As per https://github.com/openshift/enhancements/pull/1605, there was a
new field introduced in the image config spec and status which reflects
the global value to be set for imagestream import mode which is behind a
featuregate. This PR sets the status field in the image config based on
the spec setting so it can be synced by the apiserver's observedconfig
to set the import mode for imagestreams.

xref: https://github.com/openshift/cluster-openshift-apiserver-operator/pull/582 , https://github.com/openshift/openshift-apiserver/pull/443

### CODE REVIEW

**Comment by flavianmissi** [comment]
flaky tests..
/retest

**Comment by flavianmissi** [comment]
still flaking 🤔 
/retest

The changes look pretty straight forward. I assume this needs to be tested in conjunction with https://github.com/openshift/cluster-openshift-apiserver-operator/pull/582 and https://github.com/openshift/openshift-apiserver/pull/443?

**Comment by Prashanth684** [comment]
> still flaking 🤔 /retest
> 
> The changes look pretty straight forward. I assume this needs to be tested (and merged) in conjunction with [openshift/cluster-openshift-apiserver-operator#582](https://github.com/openshift/cluster-openshift-apiserver-operator/pull/582) and [openshift/openshift-apiserver#443](https://github.com/openshift/openshift-apiserver/pull/443)?

correct. In addition to that it is all behind a featuregate.

**Comment by flavianmissi** [comment]
What's the docs plan here, @Prashanth684? Do we want to involve image registry docs or is this something your team's docs will take care of? Asking because this PR requires docs approval for merging.

Similar question applies to PX.

**Comment by Prashanth684** [comment]
> What's the docs plan here, @Prashanth684? Do we want to involve image registry docs or is this something your team's docs will take care of? Asking because this PR requires docs approval for merging.
> 
> Similar question applies to PX.

We have a story targeting docs - https://issues.redhat.com/browse/MULTIARCH-4560 . @sr1kar99 is the multi-arch docs contact and will be working on this - he will work with the Image registry's docs contact if necessary. @sr1kar99 could you add the docs-approved label to this PR please?

**Comment by Prashanth684** [comment]
tagging @sferich888 for the px-approved label

**Comment by wewang58** [comment]
As discussed in slack, did a single-arch test, no critical issue found.
/label qe-approved

**Pull request merged**
