### PR TITLE
[WIP] debug flakes DO NOT MERGE

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by bparees** [comment]
this is the only PR regularly passing aws-operator......

/test e2e-aws-operator

**Comment by bparees** [comment]
@dmage we finally got the flake but the client didn't have permissions to retrieve the CRDs :(

```
logs.go:77: I0130 22:41:59.252723       1 imageconfig.go:127] unable to get image config CRD: customresourcedefinitions.apiextensions.k8s.io "images.config.openshift.io" is forbidden: User "system:serviceaccount:openshift-image-registry:cluster-image-registry-operator" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**Comment by bparees** [comment]
from the failed run:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/180/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/850

the cluster version operator log (https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/180/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/850/artifacts/e2e-aws-operator/pods/openshift-cluster-version_cluster-version-operator-59f584c75d-mpdq8_cluster-version-operator.log.gz) clearly shows the CRD was installed:

```
I0130 22:27:42.441086       1 sync_worker.go:442] Running sync for customresourcedefinition "images.config.openshift.io" (apiextensions.k8s.io/v1beta1, 10 of 254)
I0130 22:27:43.468445       1 sync_worker.go:468] Done syncing for customresourcedefinition "images.config.openshift.io" (apiextensions.k8s.io/v1beta1, 10 of 254)
```

```
I0130 22:27:49.767661       1 sync_worker.go:442] Running sync for customresourcedefinition "images.config.openshift.io" (apiextensions.k8s.io/v1beta1, 161 of 254)
I0130 22:27:50.779327       1 sync_worker.go:468] Done syncing for customresourcedefinition "images.config.openshift.io" (apiextensions.k8s.io/v1beta1, 161 of 254)
```
(not sure why it is installed twice.  Looks like possibly the openshift-network-operator is also installing it for some reason which is probably a bad practice but i don't think it's causing this problem).

Yet my read of this log is that the apiserver is claiming it doesn't know the resource type:

```
logs.go:77: E0130 22:41:59.028844       1 controller.go:208] unable to sync: unable to apply objects: failed to create object *v1.Image, Name=cluster: the server could not find the requested resource (put images.config.openshift.io cluster), requeuing
```

note the timestamp is well after the CRD creation.

Even weirder is that despite us getting a failure on the create, the next log entry shows us trying to update the object, which we'd only do if somehow the object *was* created and we saw it via a successful Get:

```
logs.go:77: E0130 22:41:59.213266       1 controller.go:208] unable to sync: unable to apply objects: failed to update object *v1.Image, Name=cluster: the server could not find the requested resource (put images.config.openshift.io cluster), requeuing
```

code is here:
https://github.com/openshift/cluster-image-registry-operator/blob/6d50255c8077fc334aa83ecdb902d8b2e9d13daa/pkg/resource/generator.go#L181-L195

with the specific implementation for dealing with images.config.openshift.io objects being here:
https://github.com/openshift/cluster-image-registry-operator/blob/6d50255c8077fc334aa83ecdb902d8b2e9d13daa/pkg/resource/imageconfig.go#L67-L114

@deads2k @mfojtik I need a theory from you that does not make this an api-server problem because right now that's all i've got...

**Comment by dmage** [comment]
```
E0131 13:38:28.003681       1 controller.go:208] unable to sync: unable to apply objects: failed to update object *v1.Image, Name=cluster: the server could not find the requested resource (put images.config.openshift.io cluster), requeuing
I0131 13:38:28.013182       1 imageconfig.go:133] image config CRD: {"metadata":{"name":"images.config.openshift.io","selfLink":"/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/images.config.openshift.io","uid":"27590fbb-255a-11e9-9288-1274b44cdfd4","resourceVersion":"22817","generation":9,"creationTimestamp":"2019-01-31T13:14:34Z"},"spec":{"group":"config.openshift.io","version":"v1","names":{"plural":"images","singular":"image","kind":"Image","listKind":"ImageList"},"scope":"Cluster","versions":[{"name":"v1","served":true,"storage":true}],"additionalPrinterColumns":[{"name":"Age","type":"date","description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata","JSONPath":".metadata.creationTimestamp"}]},"status":{"conditions":[{"type":"NamesAccepted","status":"True","lastTransitionTime":"2019-01-31T13:14:34Z","reason":"NoConflicts","message":"no conflicts found"},{"type":"Established","status":"True","lastTransitionTime":null,"reason":"InitialNamesAccepted","message":"the initial names have been accepted"}],"acceptedNames":{"plural":"images","singular":"image","kind":"Image","listKind":"ImageList"},"storedVersions":["v1"]}}
E0131 13:38:28.123645       1 controller.go:208] unable to sync: unable to apply objects: failed to update object *v1.Image, Name=cluster: the server could not find the requested resource (put images.config.openshift.io cluster), requeuing
I0131 13:38:28.145706       1 imageconfig.go:133] image config CRD: {"metadata":{"name":"images.config.openshift.io","selfLink":"/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/images.config.openshift.io","uid":"27590fbb-255a-11e9-9288-1274b44cdfd4","resourceVersion":"22817","generation":9,"creationTimestamp":"2019-01-31T13:14:34Z"},"spec":{"group":"config.openshift.io","version":"v1","names":{"plural":"images","singular":"image","kind":"Image","listKind":"ImageList"},"scope":"Cluster","versions":[{"name":"v1","served":true,"storage":true}],"additionalPrinterColumns":[{"name":"Age","type":"date","description":"CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata","JSONPath":".metadata.creationTimestamp"}]},"status":{"conditions":[{"type":"NamesAccepted","status":"True","lastTransitionTime":"2019-01-31T13:14:34Z","reason":"NoConflicts","message":"no conflicts found"},{"type":"Established","status":"True","lastTransitionTime":null,"reason":"InitialNamesAccepted","message":"the initial names have been accepted"}],"acceptedNames":{"plural":"images","singular":"image","kind":"Image","listKind":"ImageList"},"storedVersions":["v1"]}}
E0131 13:38:28.462957       1 controller.go:208] unable to sync: unable to apply objects: failed to update object *v1.Image, Name=cluster: the server could not find the requested resource (put images.config.openshift.io cluster), requeuing
```

**Pull request closed without merging**
