### PR TITLE
OCPBUGS-34399: Update rbac for featuregate

### PR DESCRIPTION
**Pull request by deepsm007**
/cc @flavianmissi 

Required by https://github.com/openshift/hypershift/pull/4123

### CODE REVIEW

**Comment by csrwng** [comment]
The e2e-hypershift failure is due to a flake in deleting cloud resources. Work to fix that is in progress. Other than that, the hypershift e2e looks good.

**Comment by flavianmissi** [comment]
according to https://github.com/openshift/cluster-image-registry-operator/pull/1056#issuecomment-2155416570 the hypershift failure is unrelated. will override
/override ci/prow/e2e-hypershift

**Pull request merged**
