### PR TITLE
Bug 2015459: Enable health check for storage driver

### PR DESCRIPTION
**Pull request by dmage**
When the registry pod cannot reach its storage, it should report about problems.

### CODE REVIEW

**Comment by wewang58** [comment]
@dmage  Hi, will cherry-pick to release 4.9 right?

**Comment by dmage** [comment]
/lgtm cancel
I want it to be reviewed by somebody from engineering.

**Comment by dmage** [comment]
@wewang58 most likely we won't backport it

**Review by ricardomaraschini — APPROVED** [review]
/lgtm

**Review by ricardomaraschini — APPROVED** [review]
/lgtm

**Pull request merged**
