### PR TITLE
[release-4.12] OCPBUGS-36033: go.*,vendor: bump go-retryablehttp

### PR DESCRIPTION
**Pull request by flavianmissi**
This is a manual backport of https://github.com/openshift/cluster-image-registry-operator/pull/1070.

---

We're manually backporting this because the bot fails to backport patches with more than 300 files changed.

### CODE REVIEW

**Comment by flavianmissi** [comment]
/retitle [release-4.12] OCPBUGS-36033: go.*,vendor: bump go-retryablehttp

**Comment by xiuwang** [comment]
@dmage And this PR, could you help review it?
Thank you!

**Pull request merged**
