### PR TITLE
Cleanup Items

### PR DESCRIPTION
**Pull request by coreydaley**
- Replace testframework constants with api constants
 - Set DeleteCompletely timeout back to AsyncOperationTimeout
 - Standardize the imageregistry/v1 api alias to be imageregistryv1
 - All CVO status messages should start with a capital letter

### CODE REVIEW

**Comment by dmage** [comment]
Nice, now we have the same constant for the operator namespace and for the registry namespace.

**Comment by bparees** [comment]
> Nice, now we have the same constant for the operator namespace and for the registry namespace.

not sure if that's sarcasm or not, but if/when we want a separate namespace for the operator we can split the constant back out.

**Pull request merged**
