### PR TITLE
IR-412: IBMCloud: Add support for endpoint overrides

### PR DESCRIPTION
**Pull request by cjschaef**
Add support to override IBM Cloud Service endpoints, when provided.

Related: https://issues.redhat.com/browse/IR-412

### CODE REVIEW

**Comment by flavianmissi** [comment]
Nice work @cjschaef. I have no objections towards merging this. Do you have a plan in regards to px, docs and qe approval?
/test e2e-ibm-ovn

**Comment by cjschaef** [comment]
@flavianmissi We will be providing some documentation for IBM Cloud Restricted Network setup and configuration. At this time, these code changes are dependent on the [installer](https://github.com/openshift/installer/pull/7632), the [CCM](https://github.com/openshift/cloud-provider-ibm/pull/47), and [MAPI](https://github.com/openshift/machine-api-provider-ibmcloud/pull/28), to even get to a point to exercise this code (I've best testing in a Disconnected environment). But there are still some items I am working on yet related to the `installer`.

I will want to work with QE on whether an environment can be configured to test IBM Cloud Disconnected, as I know it requires a good number of user configuration steps and resource setup at this time. If I am able, I'd like to also investigate extending the `ibmcos_test.go` tests, in case I can add something there. If I can do that before 4.15 FF.

**Comment by flavianmissi** [comment]
Thanks for clarifying @cjschaef.
@wewang58 is our QE currently, she might be able to help you out with a cluster. 
Maybe you already know this but you can reach the image registry team in Red Hat internal Slack at #forum-ocp-imageregistry if you need faster response.
Also recall that TRT is blocking non-critical merges for the next two weeks due to shift week and US holidays, this might affect your plans for 4.15 (it surely has affected mine).

**Comment by cjschaef** [comment]
@flavianmissi Okay, thanks for the details.

I have completed testing of these changes in my Disconnected (air-gapped) environment, using all of the changes with `installer`, `CCM`, and `MAPI`, to validate this Operator came up successfully and was using the provided overrides, and was able to communicate with the IBM Cloud Service endpoints (overrides), using IBM Cloud VPC VPE Gateways.

I'll have to guide @wewang58 on the complete setup of this Disconnected environment, and the current dependencies, and limitations (other ClusterOperators require similar changes, etc.), given the vast number of changes across components to test this code, and other components to get a happy IPI cluster (Storage, etc.), if we are going to need that kind of confirmation. It is certainly non-trivial by default, not including the requirement of these other dependent PR's.

Otherwise, not breaking existing functionality, for Public, Private, and BYON IBM Cloud IPI clusters would be good confirmation.

Okay, I believe we will be working on getting approval for these feature changes for the TRT.

**Comment by cjschaef** [comment]
https://github.com/openshift/api/pull/1657 has merged, I will attempt to update the `api` go dep and update the `ServiceName`'s to use these new enum's.

**Comment by flavianmissi** [comment]
Sounds like a plan @cjschaef. 
I'll leave it to you to sync with Wen to get QE approval. Do let me know if I can help.

**Comment by flavianmissi** [comment]
/lgtm
it looks like QE needs some help testing this.

**Comment by wewang58** [comment]
Now installer qe team is trying to provide a private cluster which support for endpoint overrides, they met some issues need time to resolve.

**Comment by wewang58** [comment]
Tested in version: 4.15.0-0.ci.test-2023-12-08-081140-ci-ln-1sdsy7t-latest, cos endpoint is override, thanks @jianlinliu  provides the cluster
/label qe-approved

**Comment by cjschaef** [comment]
It looks like the `e2e-hypershift-conformance` failures are consistent across other PR's as well.
Not sure if that issue is being addressed, or whether we can ignore the failure, given the code changes aren't involved, as other PR's suffer the same failure.

**Comment by flavianmissi** [comment]
Yep it does happen everywhere. Let's retry one last time before I make some noise.
/retest

**Comment by flavianmissi** [comment]
last error looks different than the previous.
/retest

**Comment by jeffnowicki** [comment]
@flavianmissi the `e2e-hypershift-conformance` test is failing in other PRs as well. Are we certain there isn't an issue with the test itself? The code in this PR doesn't have any `hypershift` relationship.

**Comment by flavianmissi** [comment]
oh yes there certainly is an issue with the these tests - I was just hoping they had fixed it between today and yesterday but it doesn't look like it. I'll have to find out how to skip them, will write back here when I know more.

**Comment by jianlinliu** [comment]
@cjschaef we need to backport this PR into 4.15 branch, right?

**Comment by cjschaef** [comment]
@jianlinliu It would appear so. Let me try to get that done.

/cherry-pick release-4.15

**Pull request merged**
