### PR TITLE
OCPBUGS-17060: use Recreate on operator deployment

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by flavianmissi** [comment]
need to test this
/hold

**Comment by flavianmissi** [comment]
let's see how this affects lease acquiring times during upgrade - my tests (outside the context of an upgrade) showed immediate lease acquisition.
/payload-job periodic-ci-openshift-release-master-nightly-4.14-upgrade-from-stable-4.13-e2e-aws-upgrade-ovn-single-node

**Comment by flavianmissi** [comment]
e2e failures seem unrelated.
/retest

**Comment by wking** [comment]
[Slow AWS uninstall][1] is unrelated, and I'm currently pruning IAM users in that account to speed up future rounds.

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/908/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-ovn-upgrade/1704160832172068864#1:build-log.txt%3A68

**Comment by wking** [comment]
[Failed install on AWS m6a.xlarge capacity in one of the zones selected for installation][1], which is unrelated to this pull.

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/908/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-ovn-upgrade/1704267985604055040#1:build-log.txt%3A316

**Pull request merged**
