### PR TITLE
do not setup ownerrefs for clusterscoped/cross-namespace objects

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/cluster-image-registry-operator/issues/216

### CODE REVIEW

**Comment by bparees** [comment]
/assign @dmage 

i'm surprised this wasn't breaking us, setting up ownerrefs between objects that are not all within a single namespace results in very unpredictable results.

**Comment by dmage** [comment]
@bparees our flakes are the result of deleting the image config?

/lgtm

**Comment by bparees** [comment]
> @bparees our flakes are the result of deleting the image config?

potentially yes, i think in at least some cases the issue is the imageconfig being deleted/updated (to remove the internal registry hostname) which causes a control-plane restart.  That shouldn't fail our tests, but if it takes long enough it can cause them to timeout.

That said, just not removing the imageconfig won't totally fix it, because even deleting the registry instance causes an update to the imageconfig (to remove the internal registry hostname) which will still restart the control plane.

I didn't create this PR as a direct fix for the flakes so much as something else I noticed while investigating them that definitely needs to be fixed.  But..fingers crossed it makes it better.

**Comment by bparees** [comment]
@dmage i had to add another commit to clean up how we were handling route ownership identification, ptal.

**Comment by bparees** [comment]
/hold

removeObsoleteRoutes also need to be fixed up to check for the owner annotation instead of the owner ref. 

@dmage if you know what I'm referring to and can fix this up and merge it in a new pr in the morning that'd be great, if not I'll fix it when I get in.

**Comment by dmage** [comment]
@bparees I've pushed the fix to your branch.

**Comment by bparees** [comment]
thanks @dmage 
/hold cancel

**Comment by bparees** [comment]
passed tests, manually merging to get us hopefully slightly less blocked.

**Pull request merged**
