### PR TITLE
IR-406,OCPBUGS-21853: bump k8s and openshift packages

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by flavianmissi** [comment]
this change is not user-facing.
/label docs-approved
/label px-approved

**Comment by flavianmissi** [comment]
Hi Wen, can you help us with QE approval when you get a chance? regression tests should be enough.
/assign @wewang58

**Comment by wewang58** [comment]
did regression test, no critical issue found
/label qe-approved

**Pull request merged**
