### PR TITLE
SPLAT-1721: Remove alibaba

### PR DESCRIPTION
**Pull request by jcpowermac**

### CODE REVIEW

**Comment by flavianmissi** [comment]
Thank you for taking care of this @jcpowermac!
/lgtm
/retest

**Comment by flavianmissi** [comment]
This PR needs docs approval (`/label docs-approved`). I assume your team is also taking care of documenting this for OCP in general? Don't think we need any image registry specific docs if that's the case.
We also need PX approval. Does your team have a PX contact to provide this label (`/label px-approved`)? 
What about QE?

**Comment by jcpowermac** [comment]
> This PR needs docs approval (`/label docs-approved`). I assume your team is also taking care of documenting this for OCP in general? Don't think we need any image registry specific docs if that's the case. 

The docs team has removed alibaba
https://github.com/openshift/openshift-docs/pull/78479  

> We also need PX approval. Does your team have a PX contact to provide this label (`/label px-approved`)? 
Not that I know of

> What about QE?
I would figure the image registry's QE would handle this.

**Comment by flavianmissi** [comment]
> I would figure the image registry's QE would handle this.
You are correct of course.

Can you take a look, Xiujuan? This PR changes the image registry operator so that it sets the registry as "Removed" when installed on Alibaba. Thanks!
/assign @xiuwang

**Comment by xiuwang** [comment]
Installed aws/azure/gcp cluster successfully with payload image built from this PR, no alicloud related resources(credentialsrequest) in the clusters. 
/label qe-approved

**Comment by flavianmissi** [comment]
@jcpowermac in the operator config we have Alibaba specific configuration types: https://github.com/openshift/api/blob/master/imageregistry/v1/types.go#L559-L561. Are you also planning on deprecating these as part of removing support for Alibaba?

**Comment by flavianmissi** [comment]
There are no registry specific user facing docs for Alibaba - only api docs, which should be handled by devs.
/label docs-approved

**Comment by flavianmissi** [comment]
holding until we figure out what to do with the api specific types
/hold

**Comment by jcpowermac** [comment]
> @jcpowermac in the operator config we have Alibaba specific configuration types: https://github.com/openshift/api/blob/master/imageregistry/v1/types.go#L559-L561. Are you also planning on deprecating these as part of removing support for Alibaba?

I opened this PR this past weekend but I don't expect it to be merged as-is.
https://github.com/openshift/api/pull/1990

> holding until we figure out what to do with the api specific types for Alibaba /hold

afaik that will be one of the last things we will work on

thoughts @JoelSpeed ?

**Comment by flavianmissi** [comment]
With 4.17 approaching I'm wondering if we want to remove support on 4.17 but leave the api types around, or if we're planning to backport the api types removal to 4.17... ?

Also note that you need to rebase with master @jcpowermac.

**Comment by JoelSpeed** [comment]
Removing the API will be slow, and will have to come after everything is no longer using it, I would not recommend holding the registry removals based on the API being removed

**Comment by flavianmissi** [comment]
Thanks for chiming in @JoelSpeed ! Then we just need a rebase.
/hold cancel

**Pull request merged**
