### PR TITLE
IR-471: Exposing chunksize variable to utilize docker registry config

### PR DESCRIPTION
**Pull request by deepsm007**
Trying to work around a bug for r2 integration with s3 bucket, exposing chunksize variable by utilizing the docker registry S3 driver configuration option: https://docker-docs.uclv.cu/registry/storage-drivers/s3/

/hold for https://github.com/openshift/hypershift/pull/4123  to merge

https://issues.redhat.com//browse/IR-471
/cc @flavianmissi

### CODE REVIEW

**Comment by flavianmissi** [comment]
test failures look like flakes
/retest

**Comment by flavianmissi** [comment]
still flaking
/retest

**Comment by flavianmissi** [comment]
we had to rollback the previously merged version of this PR, so we need all approvals again.
/assign @xiuwang 
for qe approval.

**Comment by xiuwang** [comment]
Hi Flavian, I want to validate the hypershift install this time, but hypershift install failed since yesterday. https://redhat-internal.slack.com/archives/CH76YSYSC/p1718334550831039 .

**Comment by flavianmissi** [comment]
hypershift e2e failure seems unrelated
/retest

**Comment by flavianmissi** [comment]
seems like hypershift CI has some issues. slack thread: https://redhat-external.slack.com/archives/C01C8502FMM/p1718674818754509

**Comment by xiuwang** [comment]
I could validate the hypershift hosted cluster is installed successfully using payload image built from this PR
```
% oc get pods -n openshift-image-registry
NAME                              READY   STATUS    RESTARTS   AGE
image-registry-74bf788c64-54vnz   1/1     Running   0          4h49m
image-registry-74bf788c64-jkcch   1/1     Running   0          4h49m
node-ca-ds9cg                     1/1     Running   0          4h52m
node-ca-h7f5n                     1/1     Running   0          4h52m
node-ca-wkzc2                     1/1     Running   0          4h51m
% oc get co image-registry
NAME             VERSION                                                AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
image-registry   4.17.0-0.test-2024-06-18-032901-ci-ln-7mj03ik-latest   True        False         False      4h49m
```

**Comment by deepsm007** [comment]
The test did pass before on this PR https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-image-registry-operator/1060/pull-ci-openshift-cluster-image-registry-operator-master-e2e-hypershift/1800708516311207936

**Comment by flavianmissi** [comment]
As Deep and Xiujuan state, this test passed previously on this PR with the same commit, and the PR also works on Hypershift outside of CI. We also confirmed with the Hypershift team that this is a known flake.
/override ci/prow/e2e-hypershift

**Pull request merged**
