### PR TITLE
IR-298: Bump k8s to 1.25.2

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
Error: error reading Route Table (rtb-0f437adcf1154a6c8): couldn't find resource
/retest

**Comment by dmage** [comment]
/assign @flavianmissi 
for lgtm

/assign @xiuwang 
for qe-approved (no user visible changes, so perhaps green CI is enough?)

**Comment by xiuwang** [comment]
Do regression test on this pr [20221025-0612 ](https://polarion.engineering.redhat.com/polarion/#/project/OSE/testrun?id=20221025-0612), no issues found.

**Pull request merged**
