### PR TITLE
[WIP] Bug 1714775: OpenAPI schema for CRD (4.1)

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

4.1.z is not fully open yet.

**Comment by adambkaplan** [comment]
/hold cancel

Now have cherry pick approvals

**Comment by adambkaplan** [comment]
/lgtm

Re-tagging

**Comment by bparees** [comment]
@dmage are you proposing this for 4.1.2?  if so, can you add "4.1.2" to the whiteboard on https://bugzilla.redhat.com/show_bug.cgi?id=1714775 ?

**Comment by dmage** [comment]
@nstielau can you put the cherry-pick-approved label?

**Comment by adambkaplan** [comment]
/hold

Our current generator is not creating top-level descriptions, leading to empty descriptions in `oc explain`

**Comment by derekwaynecarr** [comment]
prior to us picking this back in 4.1.z, can we clone the bz in master and only pick once verified there?  changes like this should be verified in master before picked back in support streams.

**Comment by dmage** [comment]
@derekwaynecarr the bug for master is https://bugzilla.redhat.com/show_bug.cgi?id=1705752

**Comment by eparis** [comment]
/lgtm cancel
(given this is not fixed in master re: https://github.com/openshift/cluster-image-registry-operator/pull/293#issuecomment-501419736)

**Comment by adambkaplan** [comment]
@dmage I noticed that openshift/installer is floating on `master` in this branch. We should change `Gopkg.toml` so that it references the `release-4.1` branch. We do not want to pull in 4.2 code here by accident.

**Comment by eparis** [comment]
/bugzilla refresh
/hold cancel
Is the bot broken?

**Comment by eparis** [comment]
This pr requires engineering team review/lgtm to move forward.

**Comment by bparees** [comment]
@dmage @adambkaplan is there still a plan to move this PR forward?

**Comment by dmage** [comment]
@bparees yes, I want to backport the CDR from master next week.

**Comment by dmage** [comment]
These commits can't be backported. github.com/openshift/crd-schema-gen doesn't have the release-4.1 branch, the branch release-4.2 is not compatible with `sigs.k8s.io/controller-tools/pkg/crd` from 4.1.

```
	origin-4.0-kubernetes-1.12.4: Could not introduce sigs.k8s.io/controller-tools (from https://github.com/openshift/kubernetes-sigs-controller-tools.git)@origin-4.0-kubernetes-1.12.4 due to multiple problematic subpackages:
	Subpackage sigs.k8s.io/controller-tools/pkg/crd does not contain usable Go code (*build.NoGoError).. (Package is required by github.com/openshift/crd-schema-gen@release-4.2.)	Subpackage sigs.k8s.io/controller-tools/pkg/genall is missing. (Package is required by github.com/openshift/crd-schema-gen@release-4.2.)
```

The new version executed from a container complains on openshift/api types:
```
Copying "vendor/github.com/openshift/api/operator/v1/"* to temporary "/go/src/github.com/openshift/cluster-image-registry-operator/598764604/pkg/apis"...
/go/src/github.com/openshift/cluster-image-registry-operator/598764604/pkg/apis/types.go:49:2: must apply pattern to a string
/go/src/github.com/openshift/cluster-image-registry-operator/598764604/pkg/apis/types_network.go:164:28: map values must be a named type, not *ast.ArrayType
error running generator
```

Older versions of `crd-schema-gen` are known to be buggy.

@bparees @adambkaplan does it worth to continue?

**Comment by adambkaplan** [comment]
@sttts do we have a better means of back-porting the CRD generators for 4.1.z?

**Comment by sttts** [comment]
The approach in https://github.com/openshift/cluster-kube-apiserver-operator/pull/562 (with a temporary GOPATH) might work for you. This decouples dependencies of the openapi generator from the project your are generating for.

**Comment by eparis** [comment]
Given the age of this, do we think we should just WONTFIX?

**Comment by adambkaplan** [comment]
@eparis spoke with @pweil- this morning - we will close as WONTFIX as this has been addressed in 4.2

**Pull request closed without merging**
