### PR TITLE
WIP - Default to EmptyDir storage

### PR DESCRIPTION
**Pull request by adambkaplan**
* If cloud provider is unknown, default to EmptyDir storage.
* Report registry as degraded if EmptyDir is used for storage.

### CODE REVIEW

**Comment by dmage** [comment]
Looks good, but in this case all other tests that use EmptyDir shouldn't define storage configuration and use default storage configuration.

**Comment by abhinavdahiya** [comment]
This also will make testing UPI substantialy difficult as they specifically set storage to emptyDir for testing.
Why does the operator degrade on EmptyDir, if it was specifically told to do so???

**Comment by bparees** [comment]
> This also will make testing UPI substantialy difficult as they specifically set storage to emptyDir for testing.  Why does the operator degrade on EmptyDir, if it was specifically told to do so???

A registry using emptydir storage should always be considered "degraded" as you are at risk of losing your content if the registry pod is evicted/rescheduled.  An admin needs to be aware of this.

Why does it make UPI testing difficult?

**Comment by abhinavdahiya** [comment]
> > This also will make testing UPI substantialy difficult as they specifically set storage to emptyDir for testing.  Why does the operator degrade on EmptyDir, if it was specifically told to do so???
> 
> A registry using emptydir storage should always be considered "degraded" as you are at risk of losing your content if the registry pod is evicted/rescheduled. An admin needs to be aware of this.

Warnings are great! but Degraded has meaning important to CVO and cluster creation complete. So if the admin chose that as storage, operator shouldn't be Degraded. 

> Why does it make UPI testing difficult?

Because it requires ci setup storage backend for metal and vsphere.

**Comment by bparees** [comment]
> Degraded has meaning important to CVO and cluster creation complete.

what meaning does it have?  available and published version are all the CVO should care about that i am aware of.  Since when does it care about Degraded and what does it do w/ that information?  Regardless, we do not want you running a cluster upgrade while using emptydir storage on your registry, you are going to make a mess of it.

> Because it requires ci setup storage backend for metal and vsphere.

that is true regardless...  on baremetal and vsphere UPI you're actually going to explicitly get *no* storage configuration at all, and the registry will not be available, and CI will need to configure storage..this requirement (post-install configuration before CI can run - essentially "day 2 admin operations") has been discussed elsewhere.

This is being done to avoid blocking IPI installs in which we cannot configure a meaningful/real storage solution(yet).  We do not want those users to fail to realize the situation they are in.

Should we distinguish between "the registry operator chose this for you because we didn't know what else to do" and "the admin configured the registry operator this way"?  Maybe.  personally i think even if you chose emptydir, you should be informed the registry is degraded because it cannot provide the level of service that is really needed.

And let me be clear on the behavior the registry is providing here:

1) IPI installs on platforms we support: storage should be configured to something "real" by the time the install is done.

2) UPI installs on cloud platforms - if usable storage credentials were supplied, storage will be configured.  if not, storage will not be configured, registry will not be available at all when install completes.

3) UPI baremetal - storage will not be configured (we have no idea what you want), registry will not be available when install completes.

4) IPI install on "unknown/unsupported" providers(ie we can't configure storage on that provider) - emptydir storage will be configured, registry is degraded.  This is being done for OpenStack for now because we don't yet support it but we do not want to block teams trying to do IPI install work on that platform.  By the end of 4.2, of course, we will, and you'll get "real" storage on OpenStack.  It is being done in general so that when 4.3 work starts and a team wants to try out an IPI install on cloud platform $FOO, the registry does not block the install.


@derekwaynecarr @smarterclayton concerns?

**Comment by dmage** [comment]
@bparees the operator can't distinguish between UPI and IPI, so we will have EmptyDir on baremetal. Essentially it's almost the same as "the storage is not configured".

**Comment by bparees** [comment]
> @bparees the operator can't distinguish between UPI and IPI, so we will have EmptyDir on baremetal. Essentially it's almost the same as "the storage is not configured".

@dmage the operator can distinguish between "bare metal" and "unknown cloud provider" though...  so on bare metal we can reasonably come up as "storage not configured"  (bare metal will never be IPI, only UPI).

**Comment by adambkaplan** [comment]
/close

Summarizing discussion with @abhinavdahiya , @bparees , @crawford , et. al.

We don't want to set `Degraded=true` or `Upgradeable=false` if the the cluster admin or the installer explicitly set `emptyDir` as storage. Setting either of these will block upgrade for the component, which we don't want to do if someone/thing explicitly set it as such.

We could do this if we use `emptyDir` as a last-resort default. However, we won't protect against data loss when the underlying nodes are upgraded, so the primary utility of setting `Degraded=true` or `Upgradeable=false` is to ensure we fail our CI tests. Unclear if this is better than having `StorageNotConfigured`.

Teams developing IPI for new cloud providers can modify the install process to set `emptyDir` as the storage for the registry to unblock the install from completing. @wking @abhinavdahiya is this process documented?

**Comment by wking** [comment]
Docs for adding install-time manifests are [here][1].  They're currently pretty sparse.

[1]: https://github.com/openshift/installer/blame/0e4119dd152586a6cfed0f8bed512ceccbdfdac3/docs/user/customization.md#L26

**Pull request closed without merging**
