### PR TITLE
Create secret before deployment

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by dmage** [comment]
```
level=warning msg="RetryWatcher - getting event failed! Re-creating the watcher. Last RV: 271"
level=fatal msg="waiting for bootstrap-complete: timed out waiting for the condition"
```
/retest

**Comment by coreydaley** [comment]
@legionus a retest isn't going to help, if you look at the test logs there is a nill pointer dereference in what looks to be `/go/src/github.com/openshift/cluster-image-registry-operator/pkg/resource/secret.go:57` (or somewhere thereabouts.

**Comment by dmage** [comment]
NewDriver didn't return an error when it had a problem. Fixed.

**Comment by dmage** [comment]
`level=fatal msg="waiting for openshift-console URL: context deadline exceeded"`
/retest

**Pull request merged**
