### PR TITLE
OCPBUGS-38842: pkg/resource: invoke update-ca-trust extract with --output

### PR DESCRIPTION
**Pull request by flavianmissi**
using this might help keep write permissions on
/etc/pki/ca-trust/extracted/pem/directory-hash.

### CODE REVIEW

**Comment by flavianmissi** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.18-e2e-aws-ovn-serial

**Comment by flavianmissi** [comment]
cluster-bot job (`launch 4.18.0-0.nightly-2024-08-22-025213,openshift/cluster-image-registry-operator#1096 aws`): https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1826622278671011840

**Comment by stbenjam** [comment]
/retitle OCPBUGS-38842: pkg/resource: invoke update-ca-trust extract with --output

**Comment by stbenjam** [comment]
My understanding from Slack is this worked around the problem, and I'd rather not leave payloads broken for 4+ days.  We can undo if a better solution is found.

/lgtm

**Comment by Prashanth684** [comment]
looks like we need this fix for 4.16 and 4.15 as well

**Pull request merged**
