### PR TITLE
Bug 2015800: fix(ibmcos): Resource key validation + update status granularly

### PR DESCRIPTION
**Pull request by hasueki**

### CODE REVIEW

**Comment by xiuwang** [comment]
This pr conducts new issue, when update the bucket only, it always show 
```
  - lastTransitionTime: "2022-01-25T06:44:11Z"
     message: 'Unable to apply resources: unable to sync storage configuration: specified
        resource key credentials does not have an attached IAM role'
     reason: Error
     status: "True"
     type: Progressing
```

And I checked the credentials, it used the aws secret, is it correct?
```
$oc exec image-registry-7bc869b865-j9dnd  -- cat /var/run/secrets/cloud/credentials
[default]
aws_access_key_id = *********
aws_secret_access_key = ****

$oc get secret  image-registry-private-configuration -o json | jq -r .data.credentials  | base64 -d
[default]
aws_access_key_id = *****
aws_secret_access_key = ***

$oc get secret installer-cloud-credentials -o json | jq -r .data
{
  "ibm-credentials.env": "***",
  "ibmcloud_api_key": "***"
}
```

**Comment by hasueki** [comment]
> This pr conducts new issue, when update the bucket only, it always show

Ah thank you for the catch. I have pushed an update to fix this issue.

> And I checked the credentials, it used the aws secret, is it correct?

Yes, this is expected behavior.

**Comment by xiuwang** [comment]
@hasueki hi, I still could reproduce the bug https://bugzilla.redhat.com/show_bug.cgi?id=2015800#c0 , the unexist bucket or  resourceKeyCRN still be synced to status.storage. 
$ oc get config.image -o jsonpath={..status.storage}  | jq
{
  "ibmcos": {
    "bucket": "wxjibm25-ggw4f-image-registry-eu-gb-eejmjvjmtkfdyyeaadwusdgfsaunexist",
    "location": "eu-gb",
    "resourceGroupName": "wxjibm25-ggw4f",
    "resourceKeyCRN": "crn:v1:bluemix:public:cloud-object-storage:global:a/fdc2e14cf8bc4d53a67f972dc2e2c861:564273f5-3ae5-465b-9314-ee24fa0b4939:resource-key:9e119f72-3505-4e11-8408-e89cc796fad8aa",
    "serviceInstanceCRN": "crn:v1:bluemix:public:cloud-object-storage:global:a/fdc2e14cf8bc4d53a67f972dc2e2c861:564273f5-3ae5-465b-9314-ee24fa0b4939::"
  }
}

**Comment by hasueki** [comment]
@xiuwang Thank you. If you are able to provide the entire status obj and relevant logs, that would be helpful in diagnosing the issue.

**Comment by xiuwang** [comment]
@hasueki Thanks to address this issue, I add info in the bug https://bugzilla.redhat.com/show_bug.cgi?id=2015800#c2 , please check.

**Comment by hasueki** [comment]
@xiuwang I have pushed an update to fix the issue and have verified on our side. Please test again and see if you are seeing better results. Thanks!

**Comment by xiuwang** [comment]
Can't reproduce the bug issues, thanks.
/label qe-approved

**Comment by dmage** [comment]
/bugzilla refresh
/override ci/prow/e2e-aws-operator
Failures are not related to this PR.

**Pull request merged**
