### PR TITLE
TRT-413: Add client certificate and key to service monitor

### PR DESCRIPTION
**Pull request by xueqzhan**
Added client certificates based on https://github.com/deads2k/openshift-enhancements/blob/master/enhancements/monitoring/client-cert-scraping.md

### CODE REVIEW

**Comment by dmage** [comment]
/lgtm

Please add a Jira issue to the title (for example, `OCPBUGS-123: ...`)

**Comment by dmage** [comment]
This is not a feature, so adding all approval labels.
/label docs-approved
/label px-approved
/label qe-approved

**Comment by flavianmissi** [comment]
@xueqzhan this one has been on hold for a while, do we still need to wait or are we good to go?

**Comment by xueqzhan** [comment]
> @xueqzhan this one has been on hold for a while, do we still need to wait or are we good to go?

Let's hold for now. We will bring in the unstream fix first.

**Pull request closed without merging**
