### PR TITLE
Verify go.mod and vendor

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by ricardomaraschini** [comment]
@dmage What is this about? Quite a lot of changes in here.

**Comment by dmage** [comment]
@ricardomaraschini it adds the new verification target `verify-deps` that verifies `go.mod`, `go.sum`, and `vendor`. It also uses `verify-gofmt` from build-machinery-go instead of the local script `hack/verify-gofmt.sh`. And bumps build-machinery-go that has all this stuff.

**Review by ricardomaraschini — APPROVED** [review]
/lgtm

**Pull request merged**
