### PR TITLE
Bug 1883502: Migrating to k8s.io/klog/v2

### PR DESCRIPTION
**Pull request by ricardomaraschini**
Kubernetes 1.19 started to use klog/v2, this commit moves the operator
to the same version.

### CODE REVIEW

**Comment by dmage** [comment]
@ricardomaraschini why are there no changes for go.sum? When we don't have components that use klog v1, lines about klog v1 should disappear.

**Comment by ricardomaraschini** [comment]
@dmage https://github.com/openshift/library-go/blob/master/go.sum#L841-L844

**Comment by dmage** [comment]
I wouldn't say that library-go affects us.

```
$ go mod graph | grep ' k8s.io/klog@'
github.com/openshift/api@v0.0.0-20200723134351-89de68875e7c k8s.io/klog@v1.0.0
github.com/openshift/api@v0.0.0-20200722170803-0ba2c3658da6 k8s.io/klog@v1.0.0
github.com/openshift/api@v0.0.0-20200728200559-811027b63048 k8s.io/klog@v1.0.0
sigs.k8s.io/controller-tools@v0.2.1 k8s.io/klog@v0.2.0
```

The latest github.com/openshift/api uses klog/v2, there is nothing we can fix, but sigs.k8s.io/controller-tools needs to be fixed. And as it is a regression, we need tests for that.

**Comment by ricardomaraschini** [comment]
> I wouldn't say that library-go affects us.
> 
> ```
> $ go mod graph | grep ' k8s.io/klog@'
> github.com/openshift/api@v0.0.0-20200723134351-89de68875e7c k8s.io/klog@v1.0.0
> github.com/openshift/api@v0.0.0-20200722170803-0ba2c3658da6 k8s.io/klog@v1.0.0
> github.com/openshift/api@v0.0.0-20200728200559-811027b63048 k8s.io/klog@v1.0.0
> sigs.k8s.io/controller-tools@v0.2.1 k8s.io/klog@v0.2.0
> ```
> 
> The latest github.com/openshift/api uses klog/v2, there is nothing we can fix, but sigs.k8s.io/controller-tools needs to be fixed. And as it is a regression, we need tests for that.

Can you see a reason why we still have `controller-tools` as a dependency? `sigs.k8s.io/controller-tools` is used by `github.com/openshift/crd-schema-gen` that is included in `tools.go`, I thought we had moved everything to or `openshift/api` or `openshift/client-go`.




> ' k8s.io/klog@'

**Comment by dmage** [comment]
@ricardomaraschini when we were removing hack/codegen we forgot about tools.go. tools.go still mentions hack/codegen

**Comment by ricardomaraschini** [comment]
> @ricardomaraschini when we were removing hack/codegen we forgot about tools.go. tools.go still mentions hack/codegen

OK, by removing `codegen` dependencies from `tools.go` we got rid of `controller-tools`.

**Pull request merged**
