### PR TITLE
IR-467: Enable Azure MSI authentication

### PR DESCRIPTION
**Pull request by bryan-cox**
This PR enables Azure MSI authentication, which will be utilized in the managed service - ARO HCP.

Fixes [IR-467](https://issues.redhat.com/browse/IR-467)

### CODE REVIEW

**Comment by flavianmissi** [comment]
Hi @bryan-cox, I think you also need to update the move-blobs command: https://github.com/openshift/cluster-image-registry-operator/blob/master/cmd/move-blobs/main.go#L317
We're planning to get rid of it, but until then I think you might not be able to run the registry on clusters configured with the new config without changing it as well.

**Comment by bryan-cox** [comment]
> Hi @bryan-cox, I think you also need to update the move-blobs command: https://github.com/openshift/cluster-image-registry-operator/blob/master/cmd/move-blobs/main.go#L317 We're planning to get rid of it, but until then I think you might not be able to run the registry on clusters configured with the new config without changing it as well.

Hey @flavianmissi - I think it should still work because of [this](https://github.com/openshift/cluster-image-registry-operator/blob/master/cmd/move-blobs/vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go#L41-L56). wdyt?

**Comment by flavianmissi** [comment]
Ah yes good point @bryan-cox! I think you are correct.

How are you planning to test this btw? I think we might need your QE's help to get access to an ARO HCP cluster 🤔 
cc @xiuwang 

/retest

**Comment by xiuwang** [comment]
Hi @flavianmissi , hypershift qe tell me I can use hypershift to provision an azure cluster with this code version by myself. I will design case and try to test.

**Comment by bryan-cox** [comment]
Hey @flavianmissi 👋🏻 - is there a good Slack channel to ask for review for this PR? 

Looks like all the tests are passing 🙌🏻

**Comment by flavianmissi** [comment]
we hangout at #forum-ocp-imageregistry, but I'll be the one reviewing your PR :) 
what kind of priority are we dealing with here? can this wait till next week?

**Comment by bryan-cox** [comment]
> we hangout at #forum-ocp-imageregistry, but I'll be the one reviewing your PR :) what kind of priority are we dealing with here? can this wait till next week?

Thanks for reviewing!

We will need this in 4.16 though we are expecting to backport similar MSI work 😅 . So if we don't get it in by branching this week, we'll just need to backport it once its reviewed (which is fine with me).

**Comment by flavianmissi** [comment]
The code looks fine so I won't hold you because a code review. 
/lgtm
Is this something we need image registry docs to write about? Or is it cover in some other docs?
And does your team have someone from PX involved in this effort? We can tag this `px-approved` ourselves but it's always good to get someone from their side involved, even if only for awareness.
The only other label required (besides docs-approved and px-approved) is qe-approved, and our QE already on it so we're good on that end.

**Comment by bryan-cox** [comment]
> The code looks fine so I won't hold you because of a code review. /lgtm Is this something we need image registry docs to write about? Or is it covered in some other docs? And does your team have someone from PX involved in this effort? We can tag this `px-approved` ourselves but it's always good to get someone from their side involved, even if only for awareness. The only other label required (besides docs-approved and px-approved) is qe-approved, and our QE already on it so we're good on that end.

Yeah we should have someone on our team cover the PX involved as this is part of a larger effort on integrating MSI with ARO HCP.

**Comment by bryan-cox** [comment]
I linked out docs contact to the Jira ticket as well.

**Comment by flavianmissi** [comment]
could you ask your folks to label the PR with the docs and px-approved in that case @bryan-cox ? Thanks!

**Comment by flavianmissi** [comment]
Hi @bryan-cox , can you have a look at https://issues.redhat.com/browse/OCPBUGS-34332 ? Xiujuan (image registry QE) found it while testing this PR.

**Comment by flavianmissi** [comment]
putting this on hold until we can figure out the bug (see my previous comment).
/hold

**Comment by bryan-cox** [comment]
Hey 👋🏻 - sorry for the delay in responding, I'm trying to wrap my head around how to test this. There was an issue in CNO blocking related traffic that may also be affecting this.

**Comment by bryan-cox** [comment]
Hey @flavianmissi and @xiuwang - would it be possible to continue on with this PR to get it merged now that the issues have been worked through?

**Comment by flavianmissi** [comment]
Hi @bryan-cox, thanks for the reminder!
From my end everything still looks good to go. I'll remove the hold so that when QE labels it the bot can merge the PR automatically.
/hold cancel

**Pull request merged**
