### PR TITLE
Infrastructure name

### PR DESCRIPTION
**Pull request by coreydaley**
Replaces #260 
I hope that the few updates that I made will resolve the issues that we were seeing with #260, but the tests will tell.

### CODE REVIEW

**Comment by coreydaley** [comment]
/assign @dmage @adambkaplan 
cc @wking

**Comment by coreydaley** [comment]
@bparees @smarterclayton Do we need to disable checking for OWNER files in the vendor directory?
https://github.com/openshift/cluster-image-registry-operator/pull/267#issuecomment-486912225

**Comment by wking** [comment]
> Do we need to disable checking for OWNER files...

Or prune non-Go, see my commit message [here][1].

[1]: https://github.com/openshift/cluster-image-registry-operator/pull/260/commits/788ebbc433e00db83f0798a9c0f86184d4f6803e

**Comment by dmage** [comment]
@coreydaley 

```
I0426 07:29:33.590569       1 bootstrap.go:38] generating registry custom resource
E0426 07:29:33.592481       1 controller.go:240] unable to sync: unable to get storage configuration from cluster install config: infrastructures "cluster" is forbidden: User "system:serviceaccount:openshift-image-registry:cluster-image-registry-operator" cannot get resource "infrastructures" in API group "" at the cluster scope, requeuing
```

It's weird that in the error message the API group is empty.

**Comment by coreydaley** [comment]
@wking Any thoughts on the error? 
https://github.com/openshift/cluster-image-registry-operator/pull/267#issuecomment-487012535

**Comment by coreydaley** [comment]
/hold 
Need to resolve this before it merges:
```
if infra.Status.Platform == configv1.AWSPlatformType {
		cfg.Storage.S3.Region = "us-east-1" // FIXME: installConfig.Platform.AWS.Region
	}
```

**Comment by coreydaley** [comment]
> > Do we need to disable checking for OWNER files...
> 
> Or prune non-Go, see my commit message [here](https://github.com/openshift/cluster-image-registry-operator/pull/260/commits/788ebbc433e00db83f0798a9c0f86184d4f6803e).

Shouldn't need to do that, it needs to be updates for all CI/CD

**Comment by lavalamp** [comment]
> @bparees @smarterclayton Do we need to disable checking for OWNER files in the vendor directory?

Yes, you do :)

**Comment by coreydaley** [comment]
Blocked by https://github.com/openshift/api/pull/300

**Comment by wking** [comment]
openshift/installer#1725 is in flight to unblock this.

**Comment by adambkaplan** [comment]
per @wking - we can push this to 4.2.
On upgrade we should do the following:
1. Look for the existing `openshiftClusterID` tag, remove if present
2. Add the new `kubernetes.io/cluster/{infraName}` tag

**Comment by wking** [comment]
I dunno if you can adjust both tags in a single, atomic operation.  If you can't, you'll want to add the `kubernetes.io/cluster/{infraName}` tag first and then remove the `openshiftClusterID` tag to avoid potentially leaking the bucket if you die mid-retag and the cluster is subsequently destroyed.

**Comment by coreydaley** [comment]
@wking @adambkaplan 
Is there a specific reason that we need to remove the old tag?  It shouldn't hurt anything to leave it alone I would think.

**Comment by wking** [comment]
> Is there a specific reason that we need to remove the old tag?

Just reducing possible user confusion by removing a tag that no longer had semantic meaning.

**Comment by coreydaley** [comment]
Blocked by https://github.com/openshift/installer/pull/1725

**Comment by coreydaley** [comment]
@dmage ptal

**Comment by coreydaley** [comment]
/retest
VPC limit exceeded

**Comment by coreydaley** [comment]
@dmage ptal, tests are passing, Skipping baremetal test as we discussed.

**Pull request merged**
