### PR TITLE
OCPBUGS-37543: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

### PR DESCRIPTION
**Pull request by rajdeepc2792**
Remerge PR for https://github.com/openshift/cluster-image-registry-operator/pull/1087 with additional fixes
Check additional fix changes using:- https://github.com/rajdeepc2792/cluster-image-registry-operator/compare/rajdeepc2792/ARO-9391...rajdeepc2792:cluster-image-registry-operator:rajdeepc2792/ARO-9391-remerge-with-fixes
Fixes:-
https://issues.redhat.com/browse/OCPBUGS-37543
&
https://issues.redhat.com/browse/ARO-9391

Changes:-
For Azure based storage account operations the Image Registry Operator is still using Azure Storage Account Access Keys generated using the Storage Accounts Client for manual mode credentials(i.e Managed Identity/Federated Identity).
This PR adds a diversion flow in operator when using federated tokens for all non Azure Stack Cloud to perform below operations:-

When creating storage account, disable the Shared Key Access.
When interacting with storage container use RBAC based authentication instead of using Shared Access Keys.
Testing:-

Unit Test Case:- No new test cases are added for the changes(Need to be performed)
Testing on 4.15 Managed Identity Cluster:-
Edited operator's deployment object to point the image to custom image-registry-operator image.
Operator and Registry pods got created and stayed in Running status successfully.
Operator and Registry pod was able to perform the operations on Storage Account and Container without fetching the Access Keys
Changing the AccountName in imageregistry.operator config created a new storage account with Shared Key Access disabled and container was also created successfully.

Testing on 4.18 Managed Identity Cluster(Additional fix):-
Performed oc patch config.image/cluster -p '{"spec":{"managementState":"Removed"}}' --type=merge successfully. Although, it was done with container/delete permission present. Fix also adds the check if container deletion fails because of PermissionsMismatch.

### CODE REVIEW

**Comment by flavianmissi** [comment]
Thank you for reopening this, and for making the necessary changes so that clusters with missing "containers/delete" permission no longer see the operator as degraded when setting managementState to Removed.
/lgtm

Putting this on hold until QE can do pre-merge testing.
/hold

**Comment by flavianmissi** [comment]
One more thing @rajdeepc2792. What do you think about separating the change to `manifests/01-registry-credentials-request-azure.yaml` into a new commit? Since we won't backport the permission change to 4.14-4.16 I think it will be easier to manually exclude the commit we don't want (which changes the permission).

**Comment by flavianmissi** [comment]
/lgtm
test failures look unrelated
/retest

**Comment by xiuwang** [comment]
/label  qe-approved

Qe checked the azure storage account creation and deletion on workload identity cluster, no  404/403 error now.
Check the read and write to azure storage on workload identity cluster , regular cluster, and ASH cluster.
Need check ARO cluster when PR merged.

**Comment by flavianmissi** [comment]
QE is doing some last minute upgrade tests, I'll remove the hold once that's finished.

**Comment by flavianmissi** [comment]
meanwhile... e2e-azure-operator failures seem strange 🤔 
```
DELETE https://imageregistryciopcx97jwk.blob.core.windows.net/ci-op-cx5gscbf-0ca04-wwdc9-image-registry-msdahxihbgoogpeborbd
        --------------------------------------------------------------------------------
        RESPONSE 403: 403 This request is not authorized to perform this operation.
        ERROR CODE: AuthorizationFailure
        --------------------------------------------------------------------------------
        ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
        RequestId:b5166d6b-d01e-005e-806c-f4f3c2000000
        Time:2024-08-22T08:22:32.9879339Z</Message></Error>
```
I haven't seen this on this PR before... hoping a retest will solve it 🤞🏼 
/retest

**Comment by sdodson** [comment]
/retitle OCPBUGS-37543: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

**Comment by sdodson** [comment]
/jira clone release-4.17 release-4.16 release-4.15 release-4.14

**Comment by sdodson** [comment]
/jira backport release-4.17 release-4.16 release-4.15 release-4.14

**Comment by flavianmissi** [comment]
e2e-aws-operator is a known flake. still waiting on e2e-azure-operator
/test e2e-aws-operator

**Comment by flavianmissi** [comment]
FTR I want to see e2e-azure-operator passing before removing the hold

**Comment by flavianmissi** [comment]
`azure_test.go:315: context deadline exceeded`
/retest

**Comment by flavianmissi** [comment]
same error from `e2e-azure-operator`:
```
client rate limiter Wait returned an error: context deadline exceeded
```
I'll try to run this on against my own cluster and see how that goes, I really want to see this tests pass as the change in this PR affects Azure.

**Comment by flavianmissi** [comment]
`TestPrivateStorageAccountVNetSubnetDiscovery` is failing the same way for me on running on my local machine against an Azure cluster:
```
E0826 11:50:51.197127       1 controller.go:379] unable to sync: unable to sync storage configuration: failed to discover vnet name, please provide network details manually: "vnet with tag 'kubernetes.io_cluster.ci-ln-wgwcwvt-1d09d-rz5j5: [owned shared]' not found", requeuing
```

I'm going to verify whether this also fails with the code from the master branch, and if it does then I'll override the failure and investigate the issue separately. If not, we'll need to dig deeper into it to find out what's up before merging.

**Comment by flavianmissi** [comment]
Triggered `e2e-azure-operator` from an unrelated PR: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-image-registry-operator/1100/pull-ci-openshift-cluster-image-registry-operator-master-e2e-azure-operator/1828050408761724928

**Comment by flavianmissi** [comment]
e2e-azure-operator is also failing on master - will override and investigate separately.
/override ci/prow/e2e-azure-operator

**Comment by flavianmissi** [comment]
Payload jobs are green: https://pr-payload-tests.ci.openshift.org/runs/ci/18659fa0-644c-11ef-8c2b-727fa466c7fd-0
/label acknowledge-critical-fixes-only

**Comment by sdodson** [comment]
/override ci/prow/e2e-aws-operator
This change is localized to azure code and that test has passed multiple times on this PR anyway.

**Pull request merged**
