### PR TITLE
Don't set global proxy status manually

### PR DESCRIPTION
**Pull request by coreydaley**
We should not need to set the global proxy status manually  anymore

### CODE REVIEW

**Comment by coreydaley** [comment]
/retest

level=error msg="Error: Error creating S3 bucket: TooManyBuckets: You have attempted to create more buckets than allowed"

**Comment by dmage** [comment]
The tests report some problems with {NO,HTTP,HTTPS}_PROXY environment variables.

**Comment by coreydaley** [comment]
> The tests report some problems with {NO,HTTP,HTTPS}_PROXY environment variables.

Yep, I think that the global proxy settings are still not being moved from spec to status automatically, i need to update the tests to dump some additional resources to see what is going on.

I meant to put this as WIP, I must have missed it.

**Comment by coreydaley** [comment]
/close

This is never going to work correctly since the operator is unmanaged while we do the testing.

**Comment by dmage** [comment]
@coreydaley which operator is unmanaged?

The proxy resource isn't updated because of the error:

```
2019/08/22 20:09:59 Failed to validate proxy 'cluster': invalid httpProxy URI: failed validating URI, no scheme for URI "clusterhttpproxy.example.com"
```

Can you try to add `http://` prefix?

**Comment by dmage** [comment]
The error you can find there: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/369/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-operator/1888/artifacts/e2e-aws-operator/pods/openshift-network-operator_network-operator-7dcfbf79d5-x2pk4_network-operator.log

**Comment by coreydaley** [comment]
Looks like the noProxy can't have a protocol on it, updated and committed.

**Pull request merged**
