### PR TITLE
Bug 1785302: Using types from openshift/api repository.

### PR DESCRIPTION
**Pull request by ricardomaraschini**
With this PR we migrate our data types to openshift/api and import them here as it is done on our current master branch. Unfortunately due to conflicts it become easier to just create a new branch/PR instead of cherry picking it from the original version.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/bugzilla refresh

@ricardomaraschini is this still work in progress?

**Comment by ricardomaraschini** [comment]
will it blend this time?

**Comment by dmage** [comment]
@ricardomaraschini can you remove WIP from the title? or is there anything else to do?

**Comment by ricardomaraschini** [comment]
OMG @dmage ! It is passing! Thank you very much!

**Pull request merged**
