### PR TITLE
[release-4.3] Bug 1808426: backport removing kubesystem configmap watch

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by dmage** [comment]
@coreydaley BZ is fine, QE need to verify the bug for master/4.4 before we can merge this backport.

**Comment by coreydaley** [comment]
@dmage thanks

**Comment by coreydaley** [comment]
Inclusion in 4.3.6 Reasoning: This pull request fixes an issue with polling the backend storage provider api every 4 seconds.  This PR also needs to merge so that #477 can merge which fixes a customer issue.

**Pull request merged**
