### PR TITLE
[release-4.15] OCPBUGS-39099: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

### PR DESCRIPTION
**Pull request by rajdeepc2792**
Alternate PR to https://github.com/openshift/cluster-image-registry-operator/pull/1106 as per slack thread https://redhat-internal.slack.com/archives/C07J2FREMEV/p1725265196921069?thread_ts=1724849147.369619&cid=C07J2FREMEV.
Only `go mod vendor` and `go mod tidy` were ran for this PR.
There was no need to bump go.opentelemetry.io/otel/exporters/otlp/otlptrace and go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc to v1.19.0 as per https://github.com/open-telemetry/opentelemetry-go/issues/4586

Note for QE
Because 4.15 is GA, we cannot backport the "containers/delete" permission. @rajdeepc2792 has wrote the code in a way that storage account deletion should still proceed [when setting managementState: Removed] even after container deletion fails due to lack of permission, so please double check that is the case. If you find that not to be the case, we will still go ahead with this backport but we will create a pre-emptive bug describing the issue with a documented workaround (which we will need to figure out). Though I'm hoping it won't come to that 😅

### CODE REVIEW

**Comment by sdodson** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-azure-ovn-serial periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-ovn-upgrade periodic-ci-openshift-release-master-ci-4.15-e2e-azure-ovn-upgrade

Ensuring tests similar to #1106 are run here as well

**Comment by flavianmissi** [comment]
/lgtm
/label backport-risk-assessed
/retitle [release-4.15] OCPBUGS-39099: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

**Comment by flavianmissi** [comment]
looks like the upgrade from 4.14 job failed in the triggered payload: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-cluster-image-registry-operator-1111-ci-4.15-upgrade-from-stable-4.14-e2e-azure-ovn-upgrade/1831048761548214272

I'll trigger another one even though the error seems unrelated.
/paylaod-job periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-ovn-upgrade

**Comment by flavianmissi** [comment]
/paylaod-job periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-ovn-upgrade

**Comment by flavianmissi** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-azure-ovn-upgrade

**Comment by sdodson** [comment]
Payload job passed, applying last label

**Pull request merged**
