### PR TITLE
OCPBUGS-26767: MULTIARCH-4074: PowerVS: update supported regions

### PR DESCRIPTION
**Pull request by hamzy**
Switch to using the "github.com/ppc64le-cloud/powervs-utils" package and the COSRegionForPowerVSRegion function provided.

### CODE REVIEW

**Comment by flavianmissi** [comment]
/lgtm
@wewang58 can you run regression for powervs?

**Comment by hamzy** [comment]
By the way, I just pushed a version that separated out the vendoring changes in case someone complained :)

**Comment by hamzy** [comment]
Also I have a process question.  We have an OCPBUG for a different cluster operator to back port the necessary fix to 4.15:
https://issues.redhat.com/browse/OCPBUGS-26555

Will we need a new bug for this back port as well?

**Comment by flavianmissi** [comment]
the bot should create a bug for you (btw you need to link a bug to this PR as well, add it to the PR title before everything).
you can just comment on this PR `/cherry-pick release-4.15` to backport it to 4.15 for example, and the bot will create the PR and the bug, then link the PR to the bug for you.

**Pull request merged**
