### PR TITLE
bump(api,client-go):

### PR DESCRIPTION
**Pull request by adambkaplan**
* Add imagepruner CRD
* Add RolloutStrategy to image registry operator config

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @coreydaley 

/cc @dmage 

This will unblock Corey and @Fedosin

**Comment by adambkaplan** [comment]
note that @Fedosin in your PR you will need to handle the empty value for the `RolloutStrategy` field - it will not be validated or defaulted server-side.

**Comment by dmage** [comment]
```
level=error msg="Error: Error waiting for AMI (ami-08892891a7aab038a) to be ready: timeout while waiting for state to become 'available' (last state: 'pending', timeout: 40m0s)"
```
/retest

**Pull request merged**
