### PR TITLE
Bug 2067995: Use OnRootMismatch for fsGroupChangePolicy

### PR DESCRIPTION
**Pull request by dmage**
This should help on installations that have millions of files on the registry volume.

### CODE REVIEW

**Comment by dmage** [comment]
/hold
maybe we should also have `io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel` in this PR.

**Review by ricardomaraschini — APPROVED** [review]
/lgtm

**Comment by ricardomaraschini** [comment]
These changes have been incorporated into https://github.com/openshift/cluster-image-registry-operator/pull/763
@dmage can you close this one?

**Pull request closed without merging**
