### PR TITLE
Renaming image registry resource

### PR DESCRIPTION
**Pull request by coreydaley**
Renaming image registry resource from instance to cluster

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees ptal

**Comment by bparees** [comment]
https://github.com/openshift/cluster-image-registry-operator/blob/master/manifests/registry-config.yaml#L5 needs to be updated too.

**Comment by bparees** [comment]
(used by people manually creating the config resource)

**Comment by coreydaley** [comment]
@bparees update pushed

**Pull request merged**
