### PR TITLE
Bug 1944762: Allow disruptions when operand has only one replica

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by wking** [comment]
[e2e-aws][1] almost passed, only failing on a crash-loop backoff pulling `registry.redhat.io/redhat/redhat-marketplace-index:v4.7`, which must be unrelated, right?  Can we:

/override ci/prow/e2e-aws

to get this landed, so I can stop closing dup bugs ;)

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/676/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws/1377437410127777792

**Comment by wking** [comment]
Hah, that timing is super weird, but the job passing seconds after I called for an override looks coincidental :p

**Comment by wzheng1** [comment]
/lgtm
/label qe-approve
Sorry for adding comments late, I have verified the bug with this pr.

**Pull request merged**
