### PR TITLE
e2e: Dump build information on failure

### PR DESCRIPTION
**Pull request by adambkaplan**
If the test build fails, dump relevant build information to the log.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

I think the build pod itself needs to be dumped. We hit the failure but it is hard to tell why the build is not trusting the internal registry.

**Comment by adambkaplan** [comment]
@dmage I see a lot of failures on the `e2e-aws-operator` job - is this test broken?

**Comment by dmage** [comment]
@adambkaplan it was broken, but 4 days ago we merged a fix for it. TestImageRegistryRemovedWithImages is flaky and it's exactly the test you're adding debug info to.

**Review by adambkaplan — COMMENTED** [review]
/hold cancel

Build pod info is now dumped on failure.

**Comment by dmage** [comment]
No customer facing changes.
/label docs-approved
/label px-approved

It shouldn't change CI pass rate, so no actions from QE are required.
/label qe-approved

**Pull request merged**
