### PR TITLE
Bug 1705752: Update crd

### PR DESCRIPTION
**Pull request by adambkaplan**
Replaces #319, rebased and with a newer bump (via `dep ensure -update`).

### CODE REVIEW

**Comment by adambkaplan** [comment]
Per conversation with @sttts - we don't _need_ a discriminator field `Type` on the storage as there are still changes needed upstream to get value out of the field.

**Comment by coreydaley** [comment]
@adambkaplan Should there be a bump commit from you? I don't see one.

**Comment by adambkaplan** [comment]
@coreydaley I squashed mine and Oleg's together.

**Comment by adambkaplan** [comment]
(the bump got a bit messy anyway on the rebase)

**Pull request merged**
