### PR TITLE
[4.1] Add cloudfront support

### PR DESCRIPTION
**Pull request by legionus**
/assign @dmage 
/hold

### CODE REVIEW

**Comment by adambkaplan** [comment]
@legionus I've created the `master-4.1` branch. You can update the PR to merge there.

@dmage I believe our tooling should fast forward this branch on top of `master` - you may want to keep an eye on that just to be sure.

**Comment by dmage** [comment]
As we don't have a long merge queue, I'd prefer just to use master when it will be open for 4.1.

**Pull request merged**
