### PR TITLE
Use Cluster Version ClusterID instead of Install Config ClusterID

### PR DESCRIPTION
**Pull request by coreydaley**
This is a temporary patch until #106 merges

### CODE REVIEW

**Comment by coreydaley** [comment]
@bparees ptal
This will get refactored some in #106

**Comment by coreydaley** [comment]
Failure due to maximum number of VPCs exceeded on AWS
@smarterclayton @bparees fyi

**Comment by bparees** [comment]
/lgtm 

thanks for jumping on this @coreydaley

**Pull request merged**
