### PR TITLE
Bug 1776665: Remove check for existence of backend storage

### PR DESCRIPTION
**Pull request by coreydaley**
Remove the check for the existence of the backend storage for the image registry

### CODE REVIEW

**Comment by coreydaley** [comment]
I am open to the removal of the public StorageExists function for each storage type, but it is probably worth leaving around just in case we need it in the future.

**Comment by adambkaplan** [comment]
@coreydaley operator tests failing because the expected status reasons are now gone. This leads to an important question - do we (as in OpenShift/k8s) consider status conditions API? Can we break a customer who is watching the reason codes for some kind of internal monitoring/scripting?

**Comment by coreydaley** [comment]
I would think that the status is more important than the reason for the purposes of a customer watching it.

**Comment by coreydaley** [comment]
/close
Superceded by #470

**Pull request closed without merging**
