### PR TITLE
[release-4.14] OCPBUGS-39100: Avoid Shared Access Key usage for Azure Storage Account when using Managed Identity based auth

### PR DESCRIPTION
**Pull request by flavianmissi**
Note that other than running go mod vendor (second commit in this PR), I also needed to make two manual changes to this PR:
1. bump go.opentelemetry.io/otel/exporters/otlp/otlptrace and go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc to v1.19.0 as per https://github.com/open-telemetry/opentelemetry-go/issues/4586 to fix an issue when running go mod tidy, this is why the vendored changes are bigger in this PR than in comparison with its sibling backports. This was also done on the PR against 4.15
2. Bring the `pkg/storage/azure/azureclient` over to 4.14. This package was created as part of an operator feature available on OCP >= 4.15, and so it doesn't exist on the 4.14 branch and had to be added manually. Go.mod and vendor files also needed to be updated to support this new package. The commits on this PR should clearly reflect what was needed, please let me know otherwise.

----

**Note for QE**
Because 4.14 is GA, we cannot backport the "containers/delete" permission. @rajdeepc2792 wrote the code in a way that storage account deletion should still proceed [when setting managementState: Removed] even after container deletion fails due to lack of permission, so please double check that is the case. If you find that not to be the case, we will still go ahead with this backport but we will create a pre-emptive bug describing the issue with a documented workaround (which we will need to figure out). Though I'm hoping it won't come to that 😅

### CODE REVIEW

**Comment by rajdeepc2792** [comment]
@flavianmissi faced same problem as in here:- https://github.com/openshift/cluster-image-registry-operator/pull/1106#issuecomment-2318289019
But the changes looks correct, `go mod vendor` and `go mod tidy` doesn't give problem with the changes present in PR.

**Comment by flavianmissi** [comment]
Checking `e2e-azure-ovn` [operator logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-image-registry-operator/1107/pull-ci-openshift-cluster-image-registry-operator-release-4.14-e2e-azure-ovn/1828773094576099328/artifacts/e2e-azure-ovn/gather-extra/artifacts/pods/openshift-image-registry_cluster-image-registry-operator-67c76f995b-fx226_cluster-image-registry-operator.log) and they're showing a bunch of these right at the end:
```
E0828 14:19:14.629603       1 controller.go:377] unable to sync: unable to sync storage configuration: storage.AccountsClient#CheckNameAvailability: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="AuthenticationFailed" Message="Authentication failed. The 'Authorization' header is missing.", requeuing
```

It does look suspicious but I don't quite get the connection with the changes here... will retest and see if the same thing happens and take it from there. It's also strange that this is first showing up on 4.14 and not in any of the later branches. 

/retest

**Comment by flavianmissi** [comment]
I thought maybe the credentials request had changed between 4.15 and 4.14, but [the changes](https://github.com/openshift/cluster-image-registry-operator/commits/release-4.15/manifests/01-registry-credentials-request-azure.yaml) are related to private endpoints, so it shouldn't affect other operators 🤔 
```
git diff release-4.15..release-4.14 -- manifests/01-registry-credentials-request-azure.yaml
diff --git a/manifests/01-registry-credentials-request-azure.yaml b/manifests/01-registry-credentials-request-azure.yaml
index 57d23c00e..7b18899d3 100644
--- a/manifests/01-registry-credentials-request-azure.yaml
+++ b/manifests/01-registry-credentials-request-azure.yaml
@@ -6,7 +6,7 @@ metadata:
   name: openshift-image-registry-azure
   namespace: openshift-cloud-credential-operator
   annotations:
-    capability.openshift.io/name: ImageRegistry+CloudCredential
+    capability.openshift.io/name: ImageRegistry
     include.release.openshift.io/ibm-cloud-managed: "true"
     include.release.openshift.io/self-managed-high-availability: "true"
     include.release.openshift.io/single-node-developer: "true"
@@ -30,23 +30,6 @@ spec:
       - Microsoft.Storage/storageAccounts/delete
       - Microsoft.Storage/storageAccounts/listKeys/action
       - Microsoft.Resources/tags/write
-      # the permissions below are only necessary when users request
-      # the operator to configure a private storage account.
-      - Microsoft.Network/privateEndpoints/write
-      - Microsoft.Network/privateEndpoints/read
-      - Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write
-      - Microsoft.Network/privateEndpoints/privateDnsZoneGroups/read
-      - Microsoft.Network/privateDnsZones/read
-      - Microsoft.Network/privateDnsZones/write
-      - Microsoft.Network/privateDnsZones/join/action
-      - Microsoft.Network/privateDnsZones/A/write
-      - Microsoft.Network/privateDnsZones/virtualNetworkLinks/write
-      - Microsoft.Network/privateDnsZones/virtualNetworkLinks/read
-      - Microsoft.Network/networkInterfaces/read
-      - Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action
-      - Microsoft.Network/virtualNetworks/subnets/read
-      - Microsoft.Network/virtualNetworks/subnets/join/action
-      - Microsoft.Network/virtualNetworks/join/action
     dataPermissions:
       - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete
       - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write
```

**Comment by flavianmissi** [comment]
looks like both azure clusters provisioning failed. the gcp failure is a persistent (but known) flake. I'm putting this on hold until we can determine the cause of the 401s on azure.
/hold
/retest

**Comment by flavianmissi** [comment]
Interesting, Raj's last run failed with a 409 error 🤔 
```
level=error msg=Error: creating/updating Record Type (Subscription: "d38f1e38-4bed-438e-b227-833f997adf6a"
level=error msg=Resource Group Name: "os4-common"
level=error msg=Dns Zone Name: "ci.azure.devcluster.openshift.com"
level=error msg=Record Type: "CNAME"
level=error msg=Relative Record Set Name: "api.ci-op-kbb0szkw-fb062"): recordsets.RecordSetsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil> 
```

**Comment by flavianmissi** [comment]
closing in favor of https://github.com/openshift/cluster-image-registry-operator/pull/1112, since it doesn't unnecessarily upgrade otel
/close

**Pull request closed without merging**
