### PR TITLE
IR-369,IR-370: support Azure workload identity

### PR DESCRIPTION
**Pull request by flavianmissi**

### CODE REVIEW

**Comment by flavianmissi** [comment]
I have now configured a cluster with workload identity and can confirm that this works 🎉 

/assign @dmage

**Comment by flavianmissi** [comment]
failure seems unrelated
/retest

**Comment by flavianmissi** [comment]
putting this on hold so we can merge it together with https://github.com/openshift/image-registry/pull/372
/hold

**Comment by flavianmissi** [comment]
test failures seems unrelated
/retest

**Comment by flavianmissi** [comment]
Changes in this PR are for interfacing with the CCO, they don't affect how end-users interact with the operator or the registry.

/label docs-approved
/label px-approved

**Comment by xiuwang** [comment]
Test with https://github.com/openshift/image-registry/pull/372 and cco 523 pr.
Could set registry to use the workload identity token manually and aws sts/ hypershift installation succeed.

**Pull request merged**
