### PR TITLE
Bug 1982611: bump aws-sdk-go to v1.38.35

### PR DESCRIPTION
**Pull request by dmage**

### CODE REVIEW

**Comment by wewang58** [comment]
Needs to update registry.svc.ci.openshift.org/ocp/builder image in https://github.com/dmage/cluster-image-registry-operator/blob/bump-aws-4.6/Dockerfile#L1

**Comment by sdodson** [comment]
@ricardomaraschini PTAL, also see @wewang58 comment about needing to update the Dockerfile

**Review by ricardomaraschini — APPROVED** [review]
/lgtm

**Pull request merged**
